### ISSUE TITLE
Error generating C# code for string lists with formatted types 

### ISSUE THREAD

**Issue by saikatguha** [Azure/autorest#1549]
Array parameters with formatted string types result in generator error.

Steps:

```
  type: array
  items:
    type: string
    format: uuid
```

Expected:
Generates code to serialize `IList<Guid>`

Actual:
`Cannot generate a formatted sequence from a non-string List parameter`

**Comment by olydis** [comment]
This might have been fixed recently. 
With the current version I get `IList<Guid?>` for your YAML.

In order to get `IList<Guid>`, AutoRest will soon support the `x-nullable` attribute:
```YAML
type: array
items:
  type: string
  format: uuid
  x-nullable: false
```
