### ISSUE TITLE
Client param with enum emits unquoted default string

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#1716]
```
  ApiVersionParameter:
    x-ms-client-name: version
    in: header
    type: string
    x-ms-parameter-location: client
    enum:
    - '2015-04-05'
    - '2014-02-14'
    default: '2015-04-05'
```
emits `this.Version = 2015-04-05;`

Without the `enum`, it emits `this.Version = "2015-04-05";` as expected
