### ISSUE TITLE
[Drafting][Code Generation] Add configuration to support generated method and model aliasing

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2309]
We need to be able to make an alias for a method and/or model types that the spec has changed, but the generated code should still contain methods/model types that are binary compatible with the original interface. 

This generally affects openapi specs that are being corrected or updated to conform to standards, yet an sdk has been released with method or model types that are not correct to our standards, yet but we don't want to break compatibility. 

This is a configuration setting -- this changes how the code is generated

~~~ markdown 
# Sample API
> see https://aka.ms/autorest

``` yaml
directive: 
  from: code-model-v1
  where: $..operationid[...]
  alias:
    name: operations_ListOperations
    deprecated: true
    
  from: code-model-v1
  where: $..operationid[...]
  alias:
    name: operations_ListOperations
    deprecated: true
   
```

~~~
