### ISSUE TITLE
Error converting value "double" to type 'System.Nullable`1[AutoRest.Swagger.Model.DataType]'

### ISSUE THREAD

**Issue by sheam** [Azure/autorest#2372]
I am trying to run ` autorest --input-file=swagger.yaml --output-folder=./generated --namespace=FieldCap.OpenInvoice --csharp` and am getting this error:

```
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value "double" to type 'System.Nullable`1[AutoRest.Swagger.Model.DataType]'. Path 'properties.quantity.type', line 63, position 22.
```

The portion of the swagger file in question is this:
```
        "quantity": {
          "description": "The maximum quantity threshold for this price item. Must be greater or equal to 0.",
          "type": "double",
          "example": "150.15"
        },
```
yaml version:
```
      quantity:
        description: The maximum quantity threshold for this price item. Must be greater or equal to 0.
        type: double
        example: 150.15
```

It is not clear to me why the parser isn't liking this. 'double' is a valid swagger type. What am I doing wrong here?
