### ISSUE TITLE
Autorest should support creating properties with 'ulong'

### ISSUE THREAD

**Issue by DeepakRajendranMsft** [Azure/autorest#2422]
Autorest should support creating properties with 'ulong' @lamchester @markcowl

**Comment by olydis** [comment]
Proposal:
``` yaml
type: integer
format: int64
minimum: 0 # or greater
```
will lead to `ulong`.
