### ISSUE TITLE
PROPOSAL: operations/properties deprecation 

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#2501]
In order to support duplicating a method with a different name, we're going to have to add a new `directive` into AutoRest.

The end form should be something like the `create-copy` directive in the example below. 

Basically, it creates a copy of a node, and allows the user to edit the object before inserting it back into the object model.

(there may be minor tweaking to this, but nothing significant)

~~~ markdown
# MyAPI for Me

> see https://aka.ms/autorest


## Duplicate a method and change the copy to the old name and mark that one deprecated.

``` yaml

directive:
 -from: code-model-v1
  
  # find the method that you want to create an alias for
  where: $..methods[?(@["#serializedName"] == "StorageAccounts_Delete")]

  # create a method that is the same except has a different name.
  # and is marked deprecated
  create-copy: > 
    $.Name = "DeleteAccount";
    $.deprecated = true;

```

~~~

/cc @kirthik @salameer @olydis
