### ISSUE TITLE
Custom List Models

### ISSUE THREAD

**Issue by skrusty** [Azure/autorest#2593]
Hi, I have a question on how to customise response types in AutoRest.

Our API returns a type PagedResponse<T> for rest methods. It's a custom list that includes the total items and pages etc. When a method in our RestAPI returns this, AutoRest is creating a new implementation for each return type.

E.g. PagedResponse<SomeItem> gets a return type called `PagedResponseSomeItem`
PagedResponse<AnotherItem> gets a return type called `PagedResponseAnotherItem`

Is there anyway to get AutoRest to use a generic implementation?

We're using the CSharp code generator.

Thanks in advance.

**Comment by fearthecowboy** [comment]
There are a couple things that can be done. can you share your OpenAPI spec and I can see how you're using it?

**Comment by skrusty** [comment]
Yeah sure, you can find it here (we're using Swagger 2.0) 

https://zapappi-publicapi-staging.azurewebsites.net/swagger/docs/v1

Thanks in advance.
Ben

**Comment by olydis** [comment]
I see, your scenario makes perfect sense to me, but unfortunately there's currently no way to make AutoRest generate generic classes from this.

**!No guarantees about the following!**
We haven't tried this before, but here's a workaround that may make you happy:
1) You'll need a [configuration file](https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md) for generation, so create one if you don't use one already. I'll glady help you create it, takes 30s to convert CLI args to an equivalent file
2) Add the following to that configuration file
``` yaml
directive:
    - from: code-model-v1
      where: $..[?(@.name.raw.startsWith('PagedResponse['))]
      transform: >-
        $.name.raw = $.name.raw.replace('[', '<').replace(']', '>');    /* C#-ify generic name */
        $.name.fixed = true;                                            /* prevent sanitizing that name */
        $.extensions = { "x-ms-external": true };                       /* don't generate the class definitions */
```
3) Provide the definition of `PagedResponse<T>` yourself (it's theoretically possible to trick AutoRest into generating it with tricks similar to the above, but way messier):
``` C#
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagedResponse<T>
    {
        public PagedResponse()
        {
        }

        public PagedResponse(int? totalItems = default(int?), IList<T> items = default(IList<T>))
        {
            TotalItems = totalItems;
            Items = items;
        }

        [JsonProperty(PropertyName = "TotalItems")]
        public int? TotalItems { get; set; }

        [JsonProperty(PropertyName = "Items")]
        public IList<T> Items { get; set; }

    }
```

Step 2 will make sure that *usages* of `PagedResponse<T>` are generated correctly, e.g.
``` C#
public static async Task<PagedResponse<SipTrunkEndpointModel>> GetTrunkEndpointsAsync(this ITrunks operations, string subscriptionId ...
```
and at the same time suppresses generation of any classes for `PagedResponse`.

Looking at the generated code, this may actually work :D One thing I'm not sure about is whether the ClientRuntime handles generic types correctly - but it mainly relies on Newtonsoft.JSON and I think that can handle it to some extent. Let us know if it works!

**Comment by skrusty** [comment]
Thanks for your very helpful reply. 

I am having a little trouble with the configuration file (not the easiest to work with). I've included it below, and the original command line args.

Currently I am getting an error, that seems to related to the directive section.

Config File: https://gist.github.com/skrusty/9587a886488e43df64f50ebbbc34f413

Original Commandline:
> autorest -Input http://localhost:36134/swagger/docs/v1 -AddCredentials -Namespace Zapappi.Client -CodeGenerator CSharp -ClientName ZapappiClient

Output
```
ERROR: Syntax Error Encountered: Syntax error: can not read a block mapping entry; a multiline key may not be an implicit key
    - file:///D:/Projects/Zapappi/Zapappi-Core/zapappi_client/Zapappi.Client/readme.md:15:37
ERROR: Syntax Error Encountered: Syntax error: end of the stream or a document separator is expected
    - file:///D:/Projects/Zapappi/Zapappi-Core/zapappi_client/Zapappi.Client/readme.md:15:5
ERROR: Syntax Error Encountered: Syntax error: expected a single document in the stream, but found more
    - file:///D:/Projects/Zapappi/Zapappi-Core/zapappi_client/Zapappi.Client/readme.md:12:16
Error occurred. Exiting.
{ Error: Error occurred. Exiting.
    at C:\Users\ben\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\parsing\literate-yaml.js:85:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ben\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at process._tickCallback (internal/process/next_tick.js:109:7) exitCode: 1 }
```
Thank you once again for your help.

**Comment by olydis** [comment]
@skrusty Nice, that looks very good already!

Two minor additions under the `csharp` object to match your original command:
```
add-credentials: true
override-client-name: ZapappiClient
```

Regarding the error: That is a YAML parsing/syntax error that indeed seems to point at the `directive` section. What I noticed: There seem to be tabs involved close to the directive section :slightly_smiling_face: Pasting the entire section to a YAML editor & validator confirmed that there is a problem, here is a sanitized version including the above change:

``` YAML
input-file: http://localhost:36134/swagger/docs/v1
csharp: # just having a 'csharp' node enables the use of the csharp generator.
  add-credentials: true
  override-client-name: ZapappiClient
  namespace: Zapappi.Client #override the namespace 
  output-folder : generated/csharp # relative to the global value.
  directive:
  - from: code-model-v1
    where: $..[?(@.name.raw.startsWith('PagedResponse['))]
    transform: >-
      $.name.raw = $.name.raw.replace('[', '<').replace(']', '>');    /* C#-ify generic name */
      $.name.fixed = true;                                            /* prevent sanitizing that name */
      $.extensions = { "x-ms-external": true };                       /* don't generate the class definitions */
```

**Comment by skrusty** [comment]
Thank you once again.

The changes have worked, in so much as autorest now outputs generated code. However it seems like the transform isn't doing anything.

I am guessing this is because the initial match isn't working in the where, which I am playing with now, but just wanted to give a quick update (although it looks fine).

Ben

**Comment by olydis** [comment]
Odd, note that the match/transformer operate on a different data structure than the swagger. I'll check on my machine again, possibly you don't have a high enough version of AuroRest installed. We'll release 2.0 today/tomorrow, it should work with that. :)

**Comment by skrusty** [comment]
I will check my version (I updated via choco last week) and try again.

FYI, the link in the docs to the query spec just takes you to the same page.

Will update shortly.
Thanks

**Comment by fearthecowboy** [comment]
@skrusty -- FYI, you're better off getting it from npm; IIRC, the chocolatey package doesn't get updated as often, and it's really just wrapping a call to npm anyway.

to get the 2.0 version before we mark it as released, just call 

``` haskell
npm install -g autorest@preview
```

**Comment by skrusty** [comment]
Fantastic! That seems to have worked. Quick look at the models and they've generated correctly, will update once I've actually tested the client deserialise.

Thank you once again (both of you).

**Comment by skrusty** [comment]
Is there any reason this might have stopped working? I am using autorest@2.0.4238 but no longer getting the correct code generated. It's doing what it did originally, which is creating a model for each generic list, and not using PagedResponse<Model>.

Thanks in advance.

**Comment by olydis** [comment]
Huh, will look into it! Directives have the chance to get broken from time to time since they hook into the internal pipeline structure which can slightly change from time to time 🙂

**Comment by skrusty** [comment]
Thanks, I've had no look getting this working, like it's totally ignored.

Cheers, Skrusty

**Comment by skrusty** [comment]
SO using version 2.0.4143 fixed the issue.

Also, i noticed that the most recent version didn't handle Streams correctly (when a rest api takes a file for example) and was trying to add it to the key value pair as a string. Ill try and provide a sample later once i've what i originally needed to do :]

Cheers

**Comment by olydis** [comment]
@skrusty Huh, seems we sanitize names a little earlier in the pipeline than before. At the time where the `directive` runs, the `[` and `]` are already replaced by `_`, so the following seems to work for me if I'm not missing something:
``` YAML
  directive:
  - from: code-model-v1
    where: $..[?(@.name.raw.startsWith('PagedResponse_'))]
    transform: >-
      $.name.raw = $.name.raw.replace('_', '<').replace('_', '>');    /* C#-ify generic name */
      $.name.fixed = true;                                            /* prevent sanitizing that name */
      $.extensions = { "x-ms-external": true };                       /* don't generate the class definitions */
```

Hope that reverts everything back to the way it was for you 🙂
