### ISSUE TITLE
Error: OperationId is required for all operations. Please add it for 'get' operation of '/locations' path.

### ISSUE THREAD

**Issue by kevinboss** [Azure/autorest#2647]
I am trying to generate the client code from the following swagger file: http://transport.opendata.ch/swagger.json

However with version

```
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
Showing All Installed Extensions

 Type       Extension Name                     Version   location
 core       @microsoft.azure/autorest-core     2.0.4147  C:\Users\kevin\.autorest\@microsoft.azure_autorest-core@2.0.4147
 extension  @microsoft.azure/autorest.csharp   2.0.21    C:\Users\kevin\.autorest\@microsoft.azure_autorest.csharp@2.0.21
 extension  @microsoft.azure/autorest.modeler  2.0.18    C:\Users\kevin\.autorest\@microsoft.azure_autorest.modeler@2.0.18
```

I get the following error:

```
FATAL: OperationId is required for all operations. Please add it for 'get' operation of '/locations' path.
FATAL: AutoRest.Core.Logging.CodeGenerationException: OperationId is required for all operations. Please add it for 'get' operation of '/locations' path.
```

Is this a problem with AutoRest or am I just incapable of using the tool? I generated source for multiple REST-APIs before, but there I was the one who added the swagger file generation. Here I don't have any control over the swagger file.

**Comment by fearthecowboy** [comment]
AutoRest uses `operationId` to determine the class name/method name for a given API.

If you want to use something like `tags`, you can use a configuration file to acheive something similar:

create an autorest configuration file:

~~~ markdown
# OpenData Transport
> see https://aka.ms/autorest

This is the AutoRest configuration file for the Transport APIs.

---

#### Basic Information 
These are the global settings for Transport APIs.

``` yaml
# list all the input OpenAPI files (may be YAML, JSON, or Literate- OpenAPI markdown)
input-file:
  - http://transport.opendata.ch/swagger.json

# this allows you to programatically tweak the swagger file before it is modeled.
directive:
  from: swagger-document # do it globally 
  where: $.paths.*.* 
  
  # set each operationId to 'Transport_<Tag>'
  transform: $.operationId = `Transport_${$.tags[0]}`
 
```
~~~
