### ISSUE TITLE
Code generation appears to do nothing.

### ISSUE THREAD

**Issue by busbina** [Azure/autorest#2686]
I am trying to generate the client using the example for petstore but nothing happens. Autorest exits as if I passed no arguments.

![screenerror2](https://user-images.githubusercontent.com/8128599/32300798-63c9ce0c-bf18-11e7-84c6-262e3a7ce369.PNG)

OS:Windows 10 v. 1709

**Comment by busbina** [comment]
I reformatted my dev box and it seems to have fixed the issue. Not sure why or how.

**Comment by Murmand** [comment]
Same issue here. But it does not generate anything only from local repository fork. The version does not matter, I forced local repository to the same version as downloaded npm package.

**This works:**
```
input-file: c:/Projects/swagger.json
csharp:
  output-folder: c:/Projects/lib
  generate-empty-classes: true
  verbose: true
```

**This does not generate anything, but no error occurs:**
```
input-file: c:/Projects/swagger.json
use: c:/Projects/autorest.csharp
output-folder: c:/Projects/lib
generate-empty-classes: true
verbose: true
```
