### ISSUE TITLE
NodeJS generation when model and operation has same name adds "Method" to method name

### ISSUE THREAD

**Issue by christav** [Azure/autorest#2687]
We have a swagger document with a path that has an operation ID of "analytics_versions". It also has a model in the definitions section named "Versions". When running autorest against this file, in the generated "Analytics" operations, the method ends up being named not "versions" as expected, but "versionsMethod".

Why does this renaming happen? They don't conflict language wise? Is there a setting I can use to turn off this logic somewhere? The old version of autorest didn't rename stuff this way and it causes a bunch of breakage in our code that was written against the code generated with the old version. This is making things hard to upgrade.

autorest versions:
```
> npx autorest --version
C:\dev\sonoma-cli\node_modules\autorest\dist\app.js
AutoRest code generation utility [version: 2.0.4166]

(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
Showing All Installed Extensions

 Type       Extension Name                     Version   location
 core       @microsoft.azure/autorest-core     2.0.4168  C:\Users\cct_000\.autorest\@microsoft.azure_autorest-core@2.0.4168
 extension  @microsoft.azure/autorest.modeler  2.0.18    C:\Users\cct_000\.autorest\@microsoft.azure_autorest.modeler@2.0.18
 extension  @microsoft.azure/autorest.nodejs   2.0.16    C:\Users\cct_000\.autorest\@microsoft.azure_autorest.nodejs@2.0.16
```

**Comment by olydis** [comment]
yesssss, the perls of having a multi-language code generation tool that tries to reuse as much logic as possible - including that for name disambiguation 😐 tagging our NodeJS team, thanks @christav for filing!

**Comment by amarzavery** [comment]
@christav - Autorest has a feature for supporting directives. In the configuration file (README.md) that sits along with the swagger spec, you can define the following directive that will replace versionsMethod with versions as the last step in the process before writing to the files on the disk.

```yaml
directive:
  - from: source-file-nodejs
    where: $
    transform: >-
                $ = $
                  .replace(/_?versionsMethod\(/g, "versions(")
                  .replace(/versionsMethodWithHttpOperationResponse\(/g, "versionsWithHttpOperationResponse(")
```

You can take a look at [this example](https://github.com/olydis/scratch/tree/master/BlobStorage#configuration) for reference.
