### ISSUE TITLE
"No Input Files Provided" after update of Autorest to 2.0.4210 

### ISSUE THREAD

**Issue by elmo61** [Azure/autorest#2741]
We have a configuration file called "sdk.md" which we call with autorest. It seems since updating to autorest 2.0.4210 that we get the following error when trying to run the command 

`autorest sdk.md`

> [Exception] No input files provided

This is happening on multiple computers that we develop on. The configuration file has not changed as part of this. It seems like its not reading any of the Configuration file settings at all. Has something changed that could cause this?

```

input-file: http://localhost:49304/swagger/v1/swagger.json

csharp:
  namespace: SubscriptionsSdk
  output-folder: Client
  add-credentials: true
  client-side-validation: false
  enable-xml: true                # enable experimental XML serialization support
  # azure-arm: true               # uncomment this line to enable code generation in the Azure flavor

```

**Comment by fearthecowboy** [comment]
My guess is that the configuration file is missing the magic string -- I fixed a bug that was related to that. There were cases where it would allow a configuration without the string in the file somewhere, and that was the cause of other problems on misidentifiyng things in other contexts.

Add a line in the file somewhere : 

``` markdown
 > see https://aka.ms/autorest

```

**Comment by elmo61** [comment]
thanks for the quick response. are you saying before the "input-file" i need "--"? 

i've tried it with the following but it doesn't work still

```
> see https://aka.ms/autorest

--input-file:http://localhost:49304/swagger/v1/swagger.json

--csharp:
      namespace: SubscriptionsSdk
      output-folder: Client
      add-credentials: true
      client-side-validation: false
      enable-xml: true                # enable experimental XML serialization support
      # azure-arm: true               # uncomment this line to enable code generation in the Azure flavor

```

**Comment by fearthecowboy** [comment]
No, it should be a string in the body of the file.

Oh, and sorry, no, there shouldn't be double dashes in the actual config file...  `--`  that was my hands expressing an emdash (ie, '–') in the my message. 

have a look at one of our config files: 

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/current/specification/consumption/resource-manager/readme.md

**Comment by furier** [comment]
Here you can see the output from cmd, first i list all files for you to see, then i cat the content of config file created with `autorest init` with only small modifications, and then I try to run 3 different autorest command to generate the client which all produce the same output...

```
	C:\temp\IN.ServiceLayer.StorageManager.Client
	λ ls -la
	total 172
	drwxr-xr-x 1 sander.struijk 1049089      0 Dec  1 10:23 .
	drwxr-xr-x 1 sander.struijk 1049089      0 Nov 30 17:45 ..
	drwxr-xr-x 1 sander.struijk 1049089      0 Nov 30 17:48 .vs
	-rw-r--r-- 1 sander.struijk 1049089   1043 Dec  1 10:20 readme.md
	-rw-r--r-- 1 sander.struijk 1049089 132367 Nov 30 17:48 swagger.json

	C:\temp\IN.ServiceLayer.StorageManager.Client
	λ cat readme.md
	﻿# StorageManager
	> see https://aka.ms/autorest

	This is the AutoRest configuration file for the API-NAME.

	---
	## Getting Started 
	To build the SDK for API-NAME, simply [Install AutoRest](https://aka.ms/autorest/install) and in this folder, run:

	> `autorest`

	To see additional help and options, run:

	> `autorest --help`
	---

	## Configuration for generating APIs

	Configuration file documentation: https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md

	---
	#### Basic Information 
	These are the global settings for the API.

	``` yaml
	# list all the input OpenAPI files (may be YAML, JSON, or Literate- OpenAPI markdown)
	input-file:
	  - swagger.json

	override-client-name: 'StorageManagerClient'
	```

	---
	#### Language-specific settings: CSharp

	These settings apply only when `--csharp` is specified on the command line.

	``` yaml $(csharp) 
	csharp:
	  namespace: 'IN.ServiceLayer.StorageManager.Client'
	  output-folder: '.'
	  azure-arm: true
	```
	C:\temp\IN.ServiceLayer.StorageManager.Client
	λ autorest
	AutoRest code generation utility [version: 2.0.4215]
	(C) 2017 Microsoft Corporation.
	https://aka.ms/autorest
	No configuration found at 'file:///C:/temp/IN.ServiceLayer.StorageManager.Client/'.
	[Exception] No input files provided.

	Use --help to get help information.

	C:\temp\IN.ServiceLayer.StorageManager.Client
	λ autorest readme.md
	AutoRest code generation utility [version: 2.0.4215]
	(C) 2017 Microsoft Corporation.
	https://aka.ms/autorest
	[Exception] No input files provided.

	Use --help to get help information.

	C:\temp\IN.ServiceLayer.StorageManager.Client
	λ autorest readme.md --csharp
	AutoRest code generation utility [version: 2.0.4215]
	(C) 2017 Microsoft Corporation.
	https://aka.ms/autorest
	   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.45)
	   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
	[Exception] No input files provided.

	Use --help to get help information.

	C:\temp\IN.ServiceLayer.StorageManager.Client
```

**Comment by fearthecowboy** [comment]
The line should be exactly like this :

``` markdown 
>  see https://aka.ms/autorest
```

[greaterthan]-[space]-s-e-e-[space]-h-t-t-p-s-[colon]-[slash]-[slash]-a-k-a-[dot]-m-s-[slash]-a-u-t-o-r-e-s-t

does `init` not put the `>` in place?

**Comment by furier** [comment]
It does, it was just my formatting here on github that removed it somehow, i put it back in and also double checked that i get the same error.

**Comment by fearthecowboy** [comment]
Can you zip the files up and attach them (or mail them to me at garretts`@`microsoft.com) so I can look into this?

**Comment by furier** [comment]
yes

**Comment by fearthecowboy** [comment]
Ok,  figured it out.

There is something clearly wrong with the `init` cmd or something; I found some (unicode?) crap in the file.

I reloaded the file you gave with DOS (cp437) encoding via vscode, and it shows what's really inside: 

~~~ markdown
´╗┐# StorageManager
>┬ásee┬áhttps://aka.ms/autorest

This is the AutoRest configuration file for the API-NAME.

---
## Getting Started┬á
To build the SDK for API-NAME, simply┬á[Install AutoRest](https://aka.ms/autorest/install) and in this folder, run:

>┬á`autorest`

To see additional help and options, run:

>┬á`autorest --help`
---

## Configuration for generating APIs

...insert-some-meanigful-notes-here...

---
#### Basic Information┬á
These are the global settings for the API.

``` yaml
# list all the input OpenAPI files (may be YAML, JSON, or Literate- OpenAPI markdown)
input-file:
  - swagger.json

override-client-name: 'StorageManagerClient'
```

---
#### Language-specific settings: CSharp

These settings apply only when┬á`--csharp`┬áis specified on the command line.

``` yaml $(csharp)┬á
csharp:
  namespace: 'IN.ServiceLayer.StorageManager.Client'
  output-folder: '.'
  azure-arm: true
```
~~~

To fix this, load the file up in vscode, and click on the `UTF-8` at the bottom and do 'save with encoding' and  select `DOS (cp437)`
