### ISSUE TITLE
Generate Models Only

### ISSUE THREAD

**Issue by hartmannr76** [Azure/autorest#2847]
I have been looking for a setting but have been unable to find it so far. Is it currently possible to generate models only for this?

For reference, in the petstore sample, I only want to generate the following files:
![image](https://user-images.githubusercontent.com/1211229/36089802-a108ae80-0fab-11e8-9093-6d0965c63735.png)

**Comment by fearthecowboy** [comment]
You can do that by putting a few things in configuration:

make a `readme.md` configuration file like this:

~~~ markdown
# Scenario: Models Only

> see https://aka.ms/autorest

``` yaml
input-file: petstore.json

directive:
  # removes all the operations from the code generation (leaves behind empty serviceclient though)
  - from: "code-model-v1" 
    where: $.operations[*]
    transform: return undefined
  
  # removes all the rest of the files that we don't want. (ie, if they say "using Models") 
  - from: source-file-csharp
    where: $
    transform: if ($.includes("using Models;")) return "";
```

~~~

**Comment by hartmannr76** [comment]
Confirmed this does exactly what I had asked, so I'll close this. I'm curious if you see this being a common scenario? I'd imagine many people having their own libs that probably call external APIs (maybe with fallbacks, retries, circuit breakers, etc) that accept plain models as inputs

**Comment by sikemullivan** [comment]
I'm receiving the following error when I use this. 

```
FATAL: csharp/cm/transform - FAILED
FATAL: Error: Error retrieving '$.operations[16]' (Error: Trying to retrieve item '16' from sequence with '15' items (index out of bounds))
Process() cancelled due to exception : Error retrieving '$.operations[16]' (Error: Trying to retrieve item '16' from sequence with '15' items (index out of bounds))
  Error: Error retrieving '$.operations[16]' (Error: Trying to retrieve item '16' from sequence with '15' items (index out of bounds))
```

**Comment by bholemaharaj** [comment]
The code listed above didn't work for me, it still generated everything and all I wanted was just the models(DTO's)
Here is my reademe.md. What is - from: code-model-v1 and  - from: source-file-csharp?

``` yaml
# it's the same options as command line options, just drop the double-dash!
input-file: input/myApi.json
powershell: true
output-folder: output/V1
namespace: CodeGen

directive:
  # removes all the operations from the code generation (leaves behind empty serviceclient though)
  - from: "code-model-v1" 
    where: $.operations[*]
    transform: return undefined
  
  # removes all the rest of the files that we don't want. (ie, if they say "using Models") 
  - from: source-file-csharp
    where: $
    transform: if ($.includes("using Models;")) return "";
```
