### ISSUE TITLE
C# code generation error when using global parameters with top level operations

### ISSUE THREAD

**Issue by natinimni** [Azure/autorest#2875]
AutoRest creates a non-compiling C# code when defining a swagger with global parameter and top\client level operation. 

Consider the following swagger:
~~~{
  "swagger": "2.0",
  "info": {
    "title": "FooBarClient",
    "version": "2016-09-01-Preview"
  },
  "x-ms-parameterized-host": {
    "parameters": [
      {
        "$ref": "#/parameters/SomeParameter"
      }
    ]
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/bar": {
      "get": {
        "operationId": "Bar",
        "responses": {"200": {"description": ""}}
      }
    },
    "/foo": {
      "get": {
        "operationId": "Foo_Get",
        "responses": {"200": {"description": ""}}
      }
    }
    
  },
  "parameters": {
    "SomeParameter": {
      "name": "someParameter",
      "in": "path",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "client"
    }
  }
}
~~~
While the generated C# code for "FooOperations" access 'SomeParameter' correctly using 'Client': 
~~~
    internal partial class FooOperations : IServiceOperations<FooBarClient>, IFooOperations
    {
        public FooBarClient Client { get; private set; }
public async Task<AzureOperationResponse> GetWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (Client.SomeParameter == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "this.Client.SomeParameter");
            }
            . . .
        }
    }
~~~
But the generated "FooBarClient" code wrongly tries to access 'SomeParameter' in the same way, using 'Client', instead of accessing it using 'this':
~~~
    public partial class FooBarClient : ServiceClient<FooBarClient>, IFooBarClient, IAzureClient
    {
        public string SomeParameter { get; set; }

        public virtual IFooOperations Foo { get; private set; }

        public async Task<AzureOperationResponse> BarWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (this.Client.SomeParameter == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "this.Client.SomeParameter");
            }
            . . .
         }
    }
~~~

This is of course a compilation error. 
Furthermore, the generated code seems to be affected by the order of the operations in the swagger file - changing the order of 'foo' and  'bar' in the swagger, results in both FooBarClient and FooOperations accessing SomeParameter using 'this' (and not 'Client') - changing the compilation error to the FooOperations class.

Note that when defining **only** top-level operations, this works well.
Am I doing something wrong here?

**Comment by fearthecowboy** [comment]
O_o 

It definitely looks like you've found a glitch here.  I'm thinking it's related to `x-ms-parameterized-host`. 

Worse, I know there are some weird bits in there that how something is used first, affected how it emitted code on subsequent use.  Pretty much every time it has to say `this.Client` it's a ratsnest in those templates.

**Comment by natinimni** [comment]
Thanks @fearthecowboy , and ETA for a fix? this is currently blocking us (Azure.Search) from shipping a new feature.

Thanks,
Nati

**Comment by fearthecowboy** [comment]
I was just looking when I can look deeper into it. 

I will try to find time to dig into this tomorrow; if it is terribly tricky, I may give you a short-term workaround fix you can stick in your configuration file.

G

**Comment by natinimni** [comment]
Thank you @fearthecowboy . 
Any updates?

**Comment by fearthecowboy** [comment]
Replace the c# code generation settings with

~~~ markdown

``` yaml $(csharp)
csharp:
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  namespace: Microsoft.Azure.Search
  clear-output-folder: true
  output-folder: $(csharp-sdks-folder)/Search/DataPlane/Microsoft.Azure.Search.Service/Generated

directive: 
  # fixes an incorrect generation in AutoRest with a parameterized host and both client and operation groups that use it.
  - from: source-file-csharp
    where: $
    transform: >
      if ( $.includes("class DataSourcesOperations") || $.includes("class IndexersOperations") || 
        $.includes("class IndexesOperations") ||  $.includes("class SynonymMapsOperations") ) 
        
        return $.
          replace(/this.SearchServiceName/g,"Client.SearchServiceName").
          replace(/this.SearchDnsSuffix/g,"Client.SearchDnsSuffix");
      return $;  
```
~~~
