### ISSUE TITLE
Example C# readme.md

### ISSUE THREAD

**Issue by kgreed** [Azure/autorest#2931]
I am using Windows 10 and am able to run the following successfully from the command line

`AutoRest -mynamespace mytrack.Client -CodeGenerator CSharp -Modeler 
Swagger -Input swagger.json -PackageName mytrack.client -AddCredentials true`

Now I want to switch to the newer syntax with a readme.md file 
I am finding the help hard to understand
Is there a simple C# example anywhere?

**Comment by kgreed** [comment]
I have been able to get the newer syntax working at a command line
`autorest --input-file=swagger.json --csharp --output-folder=gen --namespace='mytrack.client' --add-credentials`
I still am puzzling about how to make a readme.md file

**Comment by bkwdesign** [comment]
# The MyCorp MyAPI Config File
    > see https://aka.ms/autorest 

    ## Literate Config File
    > See https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md

    ## Getting Started 
      1.) Update myApi.json (you'll see in this same folder) to align with the lastest swagger definition.

      2.) To build the SDKs for The MyCorp MyAPI, simply install AutoRest via `npm` (`npm install -g autorest`) and then run:
         > `autorest readme.md`

         To see additional help and options, run:
         > `autorest --help`

      3.) After running this command, you can return to Visual Studio and turn on hidden files - include any new ones in your project and the models subdir of your project.

This is what it can look like, the good stuff is at the bottom. 

    For other options on installation see [Installing AutoRest](https://aka.ms/autorest/install) on the AutoRest github page.

    ---

    ## Configuration 
    The following are the settings for generating this API with AutoRest.
 
    ``` yaml 
    # specify the version of Autorest to use
    version: 2.0.4262 
    input-file: myApi.json

    csharp:
      output-folder: ./
      namespace: MyCorp.MyApi.Client
      override-client-name: MyApiClientClassName
      add-credentials: false 

    # (more settings here...)
    ```
