### ISSUE TITLE
name conflict in autorest codegen (C#)

### ISSUE THREAD

**Issue by northtyphoon** [Azure/autorest#3007]
Our swagger model has one type named `Task`. So the generated C# code contains a class name `Task` in `Models` namespace but it's conflicted with `System.Task`. Is there an option to customize the class name?

__Swagger__

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2018-09-01/containerregistry_build.json#L1058  

__Codegen__

**Task**<AzureOperationResponse<**Task**>> UpdateWithHttpMessagesAsync(string resourceGroupName, string registryName, string taskName, TaskUpdateParameters taskUpdateParameters, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

**Comment by fearthecowboy** [comment]
I'm working on a fix right now.

**Comment by fearthecowboy** [comment]
Ok:

Change your `readme.md` configuration (assuming this only affects the latest release):

~~~ markdown 
### Tag: package-2018-09

These settings apply only when `--tag=package-2018-09` is specified on the command line.

``` yaml $(tag) == 'package-2018-09'

csharp:
  # stop the simplifier from making Task conflict:
  skip-simplifier-on-namespace: 
    - System.Threading.Tasks

input-file:
- Microsoft.ContainerRegistry/stable/2017-10-01/containerregistry.json
- Microsoft.ContainerRegistry/stable/2018-09-01/containerregistry_build.json
```
~~~

and then install the latest `preview` build of the c# generator:

``` powershell
# remove existing extensions
autorest --reset

# install the latest preview c# extension
autorest --csharp --preview  --help

# then run the generation command as normal
... 
```
