### ISSUE TITLE
securityDefinitions does not generate related codes

### ISSUE THREAD

**Issue by wnishi-swd** [Azure/autorest#3066]
Hi, I'm trying to generate Python library for my web service.
In order to call my API, the request header must contain an API Key.
So my API spec contains `securityDefinitions` part:
```
securityDefinitions:
  api_key:
    type: apiKey
    name: X-API-Key
    in: header
````
But the generated library does not seem to expect the API Key specified by user, and
```
$ grep -r -i x-api-key
```
shows that there is no code related to it.
Is this behavior intended?
