### ISSUE TITLE
[THREAD] PowerShell Generator - Quick Questions

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#3140]
If you have some quick questions about the PowerShell Generator, ask 'em here. 

If you have an actual bug to report, go ahead and file an issue.

**Comment by fearthecowboy** [comment]
## Getting Updates
We're deep in development now, and new builds will be published every time I merge a commit, so if you want to get the latest version of the PowerShell generator, you can just run
> `autorest --reset` 
and AutoRest will remove the existing version, and will reinstall the latest beta the next time you use it.

**Comment by darrelmiller** [comment]
I am getting the following error:

```
ERROR (UnknownJsonType/LLCS2000): Schema '.schemas:4.allOf.1' is declared with invalid type 'undefined'
    - code-model-v3.yaml:1:0
C:\Users\darrmi\.autorest\@microsoft.azure_autorest.csharp-v2@1.0.106\node_modules\@microsoft.azure\autorest.csharp-v2\dist\plugin-llcsharp.js - {}
FATAL: Error: Unknown Model. Fatal.
```
I think it is related to this schema,
```yaml
    "schemas": {
      "microsoft.graph.directory": {
        "allOf": [
          {
            "$ref": "#/components/schemas/microsoft.graph.entity"
          },
          {
            "title": "directory",
            "type": "object",
            "properties": {
              "deletedItems": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/microsoft.graph.directoryObject"
                }
              }
            }
          }
```

The full OpenAPI can be found here: https://graphslice.azurewebsites.net/v1.0/$openapi?tags=directory.directory&openapiversion=3

The referenced 'microsoft.graph.entity' has type: object.  Are refs in schemas supported?
