### ISSUE TITLE
Configuration: Select multiple variants providing a list in the variant selector

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest#3193]
Example:

``` yaml
where:
  variant:
    - v1
    - v2
set:
  hidden: true
```
