### ISSUE TITLE
globalStringPath is not present in code model when generating url.json

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3338]
Schema: https://github.com/Azure/autorest.test-server/blob/master/__files/swagger/url.json

Codemodel:
```
 !OperationGroup
  $key: pathItems
  operations:
  - !Operation
    apiVersions:
    - !ApiVersion
      version: '1.0.0'
    request: !Request
      parameters:
      - *o28
      - !Parameter
        schema: *o75
        implementation: Method
        required: true
        language: !Languages
          default: !Language
            name: pathItemStringPath
            description: A string value 'pathItemStringPath' that appears in the path
            serializedName: pathItemStringPath
          csharp: !CSharpLanguage
            name: pathItemStringPath
            description: A string value 'pathItemStringPath' that appears in the path
            isNullable: false
        protocol: !Protocols
          http: !HttpParameter
            in: path
      - !Parameter
        schema: *o76
        implementation: Method
        language: !Languages
          default: !Language
            name: pathItemStringQuery
            description: A string value 'pathItemStringQuery' that appears as a query parameter
            serializedName: pathItemStringQuery
          csharp: !CSharpLanguage
            name: pathItemStringQuery
            description: A string value 'pathItemStringQuery' that appears as a query parameter
            isNullable: true
        protocol: !Protocols
          http: !HttpParameter
            in: query
      - !Parameter
        schema: *o26
        implementation: Method
        required: true
        language: !Languages
          default: !Language
            name: localStringPath
            description: should contain value 'localStringPath'
            serializedName: localStringPath
          csharp: !CSharpLanguage
            name: localStringPath
            description: should contain value 'localStringPath'
            isNullable: false
        protocol: !Protocols
          http: !HttpParameter
            in: path
      - !Parameter
        schema: *o26
        implementation: Method
        language: !Languages
          default: !Language
            name: localStringQuery
            description: should contain value 'localStringQuery'
            serializedName: localStringQuery
          csharp: !CSharpLanguage
            name: localStringQuery
            description: should contain value 'localStringQuery'
            isNullable: true
        protocol: !Protocols
          http: !HttpParameter
            in: query
      language: !Languages
        default: !Language
          name: ''
          description: ''
      protocol: !Protocols
        http: !HttpRequest
          path: /pathitem/nullable/globalStringPath/{globalStringPath}/pathItemStringPath/{pathItemStringPath}/localStringPath/{localStringPath}/globalStringQuery/pathItemStringQuery/localStringQuery
          method: get
          uri: '{$host}'
```

`o28` is the host parameter.
