### ISSUE TITLE
scope definition must not contain dot

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest#3365]
autorest v3
when the pipeline definition has dot(.) in scope, it's not working.
for example
```
pipeline-model: v3

pipeline:
    cli.common:
        input: modelerfour
        output-artifact: source-file-common
        scope: clicommon  //if change here to cli.common it's not working

    cli.common/emitter:
        input: cli.common
        scope: scope-clicommon // if change here to scope-cli.common, it's also not working

scope-clicommon: // also
    is-object: false
    output-artifact:
        - source-file-common
```
I think the problem is in here https://github.com/Azure/autorest/blob/v3/core/lib/configuration.ts#L565
Not sure if this is a bug or not, but is there a document of a list what kind of characters can't be used?
