### ISSUE TITLE
Current documentation for using `x-ms-client-flatten` doesn't follow valid JSON Reference spec - can no longer be used in ASP.NET Core 3.1 w/ Swashbuckle 5

### ISSUE THREAD

**Issue by DrEsteban** [Azure/autorest#3411]
I've learned the [current documentation](http://azure.github.io/autorest/extensions/#x-ms-client-flatten) for using `x-ms-client-flatten` doesn't actually follow valid JSON Reference specs.  Apparently, if you are referencing another schema, it is invalid to include any other tags next to the $ref: http://spec.openapis.org/oas/v3.0.2#fixed-fields-18
> This object cannot be extended with additional properties and any properties added SHALL be ignored.
```json
"definitions": {
  "template": {
    "properties": {
      "name": {
        "type": "string"
      },
      "properties": {
        "x-ms-client-flatten": true,  //invalid!
        "$ref": "#/definitions/templateProperties"
      }
    }
  }
}
```

The matter is made worse because OpenAPI.NET _enforces_ a valid spec, and if a Reference is specified they will refuse to serialize any other property: https://github.com/microsoft/OpenAPI.NET/issues/393

AutoREST should update their documentation on how to use this extension in a valid way, particularly when using the latest Swashbuckle 5 with OpenAPI.NET.  Because as it stands, ASP.NET Core 3.1 can _only_ use Swashbuckle v5, and Swashbuckle v5 has chosen to rely on OpenAPI.NET for object modeling and serialization.  This effectively means it's **impossible** to specify this extension in ASP.NET Core 3.1 w/ Swashbuckle.

**Comment by fearthecowboy** [comment]
This is indeed a painful point about OpenAPI, .

This happens in a handful of occasions, and there is no way to describe it in the spec. (ie, imagine a Car object that has two properties that is of type Color, (which has a description), but they describe two colors of the Car - body color, and interior color. In the spec it's not "legal" to add a description to the property itself, even though there is no other way to appropriately describe it. 

It is possible to use an autorest configuration file to add the attribute during generation time.

> cfg.yaml 

``` yaml
---
directive:
  - from: swagger-document      
    where $.definitions.template.properties.properties         
    transform:  return $['x-ms-client-flatten] = true        

  - from: swagger-document      
    where $.definitions.someother.properties.properties         
    transform: return $['x-ms-client-flatten]   = true

``` 

`autorest --input-file:input.json cfg.yaml `
(or if you're using a literate config file for an azure service, just put that in a yaml block
