### ISSUE TITLE
using autorest with a config file throws a Syntax error

### ISSUE THREAD

**Issue by Tobel158** [Azure/autorest#3485]
Hello ,

I am trying to generate a c# client with autorest using a config file and directives but I keep getting ERROR: Syntax error: end of the stream or a document separator is expected. 
- file:///C:/Git/AutoRestScripts/newSwaggerJson.json:1:1
This is whats in my .md config file 
> see https://aka.ms/autorest 

``` yaml 
version: 3.0.6187
input-file: newSwaggerJson.json
csharp:
    output-folder: 'AutoRestGenerated'
    namespace: prbService
    add-credentials: true
directive:
    -  from: source-file-csharp
        where: $
        transform: "\n"
        return: '$.replace( /(\s+)BaseUri = new System.Uri.*/g, "");'
```
I would appreciate any help
