### ISSUE TITLE
Feature request: Add an swagger extension to support xml tag with attributes and value

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/autorest#3535]
Swagger specifications (both 2.0 and 3.0) don't support xml tags that have both an attribute and a value. For instance, this tag of  ServiceBus Namespace API:
```xml
<title type="text">the title</title>
```
There is an open api issue: https://github.com/OAI/OpenAPI-Specification/issues/630.

Is it possible to have an extension in swagger file so autorest can generate the correct model class and msrest can serialize/deserialize?

**Comment by daviwil** [comment]
@lmazuel spoke about this over Teams, we think a good approach for now is to use an extension to indicate when a property should be treated as the text body of an XML element.  Here's an example:

*Swagger input:*

```
        "message": {
          "type": "string",
          "xml": {
            "x-autorest-text": true
          }
        }
```

*CodeModel output:*
```
    - !<!StringSchema> &ref_7
      type: string
      apiVersions:
        - !<!ApiVersion> 
          version: '2016-02-29'
      serialization:
        xml:
          attribute: false
          wrapped: false
          extensions:
            x-xml-text: true
      language: !<!Languages> 
        default:
          name: ErrorMessage
          description: ''
      protocol: !<!Protocols> {}
```

AutoRest passes the `x-xml-text` extension straight through to the CodeModel (it ends up under the `xml.extensions` sub-object) so the Python generator should be able to pick that up and use it to map the XML appropriately.  Once the OpenAPI folks standardize on an approach we can add official support for it in AutoRest.
