### ISSUE TITLE
multiple outputs in markdown file results in Error: Cannot resolve pipeline stage 'openapi-document/identity'.

### ISSUE THREAD

**Issue by darthrcf** [Azure/autorest#3608]
Version: 3.0.6247
Core Version: 3.0.6320
NodeJs Version: 10.16.3 (tried on 12.8 as well)

When I remove an output for either charp or powershell it works as advertised, when both are present results in the Error: Cannot resolve pipeline stage 'openapi-document/identity'.

Markdown file contents:

# The Client Configuration Markdown File (This file is best opened in Visual Studio Code to avoid Unicode formatting problems)
> see https://aka.ms/autorest

..... instructions - removed for brevity

``` yaml 


input-file: my.json
namespace: My.Client

csharp:
    output-folder: My.Client
    log-file: log-csharp-client.txt 
	

powershell:
  clear-output-folder: true
  output-folder: My.Client.Powershell
  log-file: log-powershell-client.txt

**Comment by davidkaya** [comment]
I had a same issue however changing the configuration from 

``` yaml
nodejs:
  output-folder: ../../generated/javascript/GeneratedNodejs
  generate-package-json: false

csharp:
  output-folder: ../../generated/dotnet/GeneratedCsharp
```

to

``` yaml
nodejs:
  - output-folder: ../../generated/javascript/GeneratedNodejs
     generate-package-json: false

csharp:
  - output-folder: ../../generated/dotnet/GeneratedCsharp
```

fixed the issue :)
