### ISSUE TITLE
Having multiple swaggers with different api-version usages result in inconsistent api-version parameter

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3634]
Compare:
 
```
input-file:
    -  https://raw.githubusercontent.com/Azure/azure-rest-api-specs/257f060be8b60d8468584682aa2d71b1faa5f82c/specification/communication/data-plane/Microsoft.CommunicationServicesAdministration/preview/2020-07-20-preview1/communicationservicesadministration.json
    -  https://raw.githubusercontent.com/Azure/azure-rest-api-specs/838c5092f11e8ca26e262b1f1099d5c5cdfedc3f/specification/communication/data-plane/Microsoft.CommunicationServicesIdentity/preview/2020-07-20-preview2/CommunicationIdentity.json
title: commClient
```
vs
 
```
input-file:
    -  https://raw.githubusercontent.com/Azure/azure-rest-api-specs/838c5092f11e8ca26e262b1f1099d5c5cdfedc3f/specification/communication/data-plane/Microsoft.CommunicationServicesIdentity/preview/2020-07-20-preview2/CommunicationIdentity.json
title: commClient
```
 
```
- !<!Parameter> 
            schema: *ref_128
            implementation: Method
            origin: 'modelerfour:synthesized/api-version'
            required: true
            language: !<!Languages> 
              default:
                name: apiVersion
                description: Api Version
                serializedName: api-version
            protocol: !<!Protocols> 
              http: !<!HttpParameter> 
                in: query
  constants:
    - !<!ConstantSchema> &ref_128
      type: constant
      value: !<!ConstantValue> 
        value: 2020-07-20-preview1
      valueType: *ref_0
      language: !<!Languages> 
        default:
          name: ApiVersion20200720Preview1
          description: Api Version (2020-07-20-preview1)
      protocol: !<!Protocols> {}
```

vs

```
- !<!Parameter> &ref_10
    schema: *ref_8
    implementation: Client
    origin: 'modelerfour:synthesized/api-version'
    required: true
    language: !<!Languages> 
      default:
        name: apiVersion
        description: Api Version
        serializedName: api-version
    protocol: !<!Protocols> 
      http: !<!HttpParameter> 
        in: query
```
