### ISSUE TITLE
Add support to disable flattening a model

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest#3636]
**Describe the issue**
In m3, we could disable flattening a model through a configuration as below in readme.md. And this feature is very useful for breaking cycle reference and supporting polymorphism.
```
directive:
  - no-inline:
    - IedmStructuredType
```
For m4, we expect when this configuration is set, the model is marked as skip-inline for further handling by powershell generator.
```
                language:
                  default:
                    name: IedmStructuredType
                    description: ''
                    skip-inline: true //add this if IedmStructuredType is configured as no-inline in readme.md
```
