### ISSUE TITLE
Duplicate Operation 'List' detected when generating code for Resources

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest#3653]
@pakrym, as Allen already told you there're issues when using `batch` for Resources RP, so I tried `input-file`, but got error as below:

**autorest.md**
``` yaml
azure-arm: true
input-file:
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-11-01/subscriptions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyDefinitions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policySetDefinitions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/preview/2019-10-01-preview/deploymentScripts.json
modelerfour:
    lenient-model-deduplication: true
```
**Error detial**

EXEC : error (): Duplicate Operation 'List' detected. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
FATAL : error : 1 errors occured -- cannot continue. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
EXEC : error : Plugin checker reported failure. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
C:\AME\work-azure-net-sdk\eng\CodeGeneration.targets(24,5): error MSB3073: The command "npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6222/autorest-3.0.6222.tgz --version=3.0.6282 C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200513.39/autorest-csharp-v3-3.0.0-dev.20200513.39.tgz --output-folder=C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src --title=Azure.Management.Resource --namespace=Azure.Management.Resource --shared-source-folder=C:\AME\work-azure-net-sdk\eng\../sdk/core/Azure.Core/src/Shared/ --verbose" exited with code 1. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
