### ISSUE TITLE
Parameter with no property (but having parent schema with 3 properties) get flattened to nothing

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest#3654]
**Describe the issue**
Parameter `NotebookWorkspaceCreateUpdateParameters` is schema with no property (but it has a parent schema `ARMProxyResource`, with 3 properties), It gets flattened to nothing.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json#L363

Output of m4 (see `flattened: true`)
```
          - parameters:
              - schema: *ref_2
                flattened: true
                implementation: Method
                required: true
                language:
                  default:
                    name: notebookCreateUpdateParameters
                    description: The notebook workspace to create for the current database account.
                protocol:
                  http:
                    in: body
                    style: json
```

Maybe we should not flatten a parameter of schema having parent schema?

** REQUIRED ** 
**ModelerFour** version: 4.13.351
**AutoRest-core** version: 3.0.6282
**CommandLine** : ` autorest --input-file=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json --payload-flattening-threshold=1`
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json
