### ISSUE TITLE
Consider adding a convenient way to remove the header. 

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3679]
Headers commonly defined by policies and not parameters are still defines in swagger and removing them from operation parameters seem to be pretty common.

**Comment by timotheeguerin** [comment]
Looking at this issue that is related https://github.com/Azure/autorest/issues/3440, I don't see a good way to be able to handle returning `undefined` to remove an item from the list.

However you can already do this as of today using `.filter`
```
directive:
  - from: swagger-document
    where: $.paths..headers
    transform: >
      return $.filter(x=> x.name !== "MyHeaderNameToRemove")
```

I guess this could potentially be simplified with something of the sort
```
directive:
  - from: swagger-document
    where: $.paths..headers
    filter:  $.name !== "MyHeaderNameToRemove"
```
What do you think?
