### ISSUE TITLE
CodeModel from test swagger paging.json misses 'serializationFormats' and 'usage' in ObjectSchema

### ISSUE THREAD

**Issue by sacheu** [Azure/autorest#3708]
In code model from test swagger paging.json, it misses 'serializationFormats' and 'usage' in ObjectSchema.
I think per schema of code model, they are both required properties.

In fact, I don't see where this ObjectSchema is used anywhere else in the code model.

Because of this issue, we need to change how we build ObjectSchema in AutorestSchema (support when  'serializationFormats' and 'usage' are missing)

```
    - !<!ObjectSchema> 
      type: object
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      properties:
        - !<!Property> 
          schema: *ref_24
          serializedName: status
          language: !<!Languages> 
            default:
              name: status
              description: The status of the request
          protocol: !<!Protocols> {}
      language: !<!Languages> 
        default:
          name: OperationResult
          description: ''
          namespace: ''
      protocol: !<!Protocols> {}

```
[paging-code-model-v4.yaml.log](https://github.com/Azure/autorest/files/5618722/paging-code-model-v4.yaml.log)
