### ISSUE TITLE
Code model for test swagger body-array miss 

### ISSUE THREAD

**Issue by sacheu** [Azure/autorest#3710]
In code model for body-array, the operation `GetComplexItemNull` is testing a case where it get an array of Complex object (`Product` in this case), but there can be null item in the response.

From the code model file, the response of GetComplexItemNull is referring `ref_110`,

In ref_110 schema, the definition is , and that does not have `      nullableItems: true ` .

Where as in the same code mode, the ArrayOfString, it does have `nullableItems` set to true.
So I think the issue is with an array of Complex object, and array of basic type (e.g. String) works.

```
   - !<!ArraySchema> &ref_110
      type: array
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      elementType: *ref_24
      language: !<!Languages> 
        default:
          name: ArrayOfProduct
          description: 'Array of complex type with null item [{''integer'': 1 ''string'': ''2''}, null, {''integer'': 5, ''string'': ''6''}]'
      protocol: !<!Protocols> {}

```
