### ISSUE TITLE
Modeler4 does not apiVersion in Swagger and synthesizes its own

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest#3762]
**Describe the bug**
I was attempting to generate code to test the following testserver swagger for autorest.swift:(https://github.com/Azure/autorest.testserver/blob/master/swagger/validation.json)

it contains an apiVersion parameter definition
```
"ApiVersionParameter": {
      "name": "apiVersion",
      "in": "query",
      "description": "Required string following pattern \\d{2}-\\d{2}-\\d{4}",
      "required": true,
      "type": "string",
      "pattern": "\\d{2}-\\d{2}-\\d{4}"
    }
```

The test is supposed to verify that the pattern validation is correctly applied to apiVersion.

However, modeler4 creates a synthesized apiVersion and does not include the specified metadata. Instead, it includes this an an unreferenced string schema:

** Synthesized ApiVersion**
```
  - !<!Parameter> &ref_24
    schema: *ref_19  ### THIS IS A CONSTANT STRING SCHEMA ###
    implementation: Client
    origin: 'modelerfour:synthesized/api-version'
    required: true
    language: !<!Languages> 
      default:
        name: apiVersion
        description: Api Version
        serializedName: apiVersion
    protocol: !<!Protocols> 
      http: !<!HttpParameter> 
        in: query
```

**Orphaned ApiVersion Schema**
```
    - !<!StringSchema> ### NOTE NO REFERENCE HERE! ###
      type: string
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      pattern: '\d{2}-\d{2}-\d{4}'
      language: !<!Languages> 
        default:
          name: String
          description: ''
      protocol: !<!Protocols> {}
```

**Expected behavior**
The generated ApiVersion schema should incorporate any customizations present in the Swagger either by merging them or by having the schema reference the orphaned string schema instead of generating its own constant schema.

**Additional context**
The Python test case for this is marked to expect failure, but in reality this test should be able to pass.

cc/ @daviwil @iscai-msft
