### ISSUE TITLE
Naming rules not applied to all schema names

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3786]
When running https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/resources/Azure.ResourceManager.Resources/src/autorest.md

We get 

```
schema: !<!ObjectSchema> &ref_360
                    type: object
                    apiVersions:
                      - !<!ApiVersion> 
                        version: '2015-12-01'
                    properties:
                      - !<!Property> 
                        schema: *ref_17
                        serializedName: provider
                        language: !<!Languages> 
                          default:
                            name: provider
                            description: 'Service provider: Microsoft.Features'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_18
                        serializedName: resource
                        language: !<!Languages> 
                          default:
                            name: resource
                            description: 'Resource on which the operation is performed: Profile, endpoint, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_19
                        serializedName: operation
                        language: !<!Languages> 
                          default:
                            name: operation
                            description: 'Operation type: Read, write, delete, etc.'
                        protocol: !<!Protocols> {}
                    serializationFormats:
                      - json
                    usage:
                      - output
                    extensions:
                      x-internal-autorest-anonymous-schema:
                        anonymous: true
                    language: !<!Languages> 
                      default:
                        name: Operation-display <----------------------------------
                        description: The object that represents the operation.
                        namespace: ''

```

And 

```
schema: !<!ObjectSchema> &ref_23
                    type: object
                    apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-10-01'
                      - !<!ApiVersion> 
                        version: '2019-11-01'
                    properties:
                      - !<!Property> 
                        schema: *ref_17
                        serializedName: provider
                        language: !<!Languages> 
                          default:
                            name: provider
                            description: 'Service provider: Microsoft.Resources'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_18
                        serializedName: resource
                        language: !<!Languages> 
                          default:
                            name: resource
                            description: 'Resource on which the operation is performed: Profile, endpoint, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_19
                        serializedName: operation
                        language: !<!Languages> 
                          default:
                            name: operation
                            description: 'Operation type: Read, write, delete, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_20
                        serializedName: description
                        language: !<!Languages> 
                          default:
                            name: description
                            description: Description of the operation.
                        protocol: !<!Protocols> {}
                    serializationFormats:
                      - json
                    usage:
                      - output
                    extensions:
                      x-internal-autorest-anonymous-schema:
                        anonymous: true
                    language: !<!Languages> 
                      default:
                        name: OperationDisplay  <----------------------------------
                        description: The object that represents the operation.
                        namespace: ''
```

Not applying naming rules causes the deduplicator to skip this model.

When C# generator runs it applies name cleanup rules resulting in two different models with the same name.

This is a regression after updating to `4.15.442` from `4.15.423`

![image](https://user-images.githubusercontent.com/1697911/104792885-de194700-5754-11eb-9aa2-d77e57f61bf2.png)

Blocking us from taking generator updates.
