### ISSUE TITLE
Required flag on "type": "object", "format": "file" parameter ignored

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3798]
Repro:

use `body-formdata.json` but change required to false.

```jsonc
 "parameters": [
          {
            "name": "fileContent",
            "description": "File to upload.",
            "required": false, //<------
            "in": "body",
            "schema": {
                "type": "object",
                "format": "file"
            }
          }
        ],

```

Code model would still have `required: true`
```yaml
        - !<!Parameter> &ref_15
                schema: *ref_14
                implementation: Method
                required: true #<-----------
                language: !<!Languages> 
                  default:
                    name: fileContent2
                    description: File to upload.
                protocol: !<!Protocols> 
                  http: !<!HttpParameter> 
                    in: body
                    style: binary
```
