### ISSUE TITLE
Optional enums with one value should not be of type CONSTANT

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest#3851]
If an enum is non-expandable and is required, it should be considered as a constant. But if it's optional, it's not quite a constant because sending a `null` on the wire has a different meaning than sending the only allowed value. 

For example, Swagger
```json
    "EncryptionAlgorithm": {
      "name": "x-ms-encryption-algorithm",
      "x-ms-client-name": "encryptionAlgorithm",
      "type": "string",
      "in": "header",
      "required": false,
      "enum": [
        "AES256"
      ],
      "x-ms-enum": {
        "name": "EncryptionAlgorithmType",
        "modelAsString": false
      },
      "x-ms-parameter-location": "method",
      "x-ms-parameter-grouping": {
        "name": "cpk-info"
      },
      "description": "The algorithm used to produce the encryption key hash. Currently, the only accepted value is \"AES256\". Must be provided if the x-ms-encryption-key header is provided."
    },
```

(from https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2020-06-12/blob.json#L11769)

currently produces the following in modeler four:
```yaml
- &id029
  apiVersions: []
  clientDefaultValue: AES256
  extensions: {xmsAzureResource: false, xmsClientFlatten: false,
    xmsFlattened: false, xmsLongRunningOperation: false,
    xmsSkipUrlEncoding: false}
  flattened: false
  implementation: METHOD
  language:
    default: {description: 'The algorithm
        used to produce the encryption key
        hash. Currently, the only accepted
        value is "AES256". Must be provided
        if the x-ms-encryption-key header
        is provided.', name: encryptionAlgorithm,
      serializedName: x-ms-encryption-algorithm}
    java: {description: 'The algorithm used
        to produce the encryption key hash.
        Currently, the only accepted value
        is "AES256". Must be provided if the
        x-ms-encryption-key header is provided.',
      name: encryptionAlgorithm, serializedName: x-ms-encryption-algorithm}
  nullable: false
  operation: *id014
  protocol:
    http: {in: Header}
  required: false
  schema: &id041 !!com.azure.autorest.extension.base.model.codemodel.ConstantSchema
    apiVersions:
    - {version: '2020-06-12'}
    language:
      default: {description: '', name: EncryptionAlgorithmType}
    protocol: {}
    type: CONSTANT
    value: {value: AES256}
    valueType: *id018
```

as if it's a constant.

using modeler 4.15.447.
