### ISSUE TITLE
Configuration ability to use directive: without array format

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#3971]
Right now can't declare directive in a required configuration file without using an array

```yaml
# Does not work
directive: 
  from: ...

# Works
directive: 
  - from: ...
```

Solution should just be to start each file with a default 
```ts
{
directives: []
}
```
