### ISSUE TITLE
Casing lost for enum values

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#3979]
Found building synapse.  Swagger for reference is here.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/data-plane/Microsoft.Synapse/preview/2019-06-01-preview/artifacts.json

For some choices, the casing is lost for some choice values.  Not the actual value sent over-the-wire, the value to be used as one of the enumerated type values.  Here's an example

```json
"order": {
  "description": "Sorting order of the parameter.",
  "type": "string",
  "enum": [
    "ASC",
    "DESC"
  ],
  "x-ms-enum": {
    "name": "RunQueryOrder",
    "modelAsString": true
  }
}
```

Produces a `Choice` type with two `ChoiceValue`

```yaml
choices:
  - value: ASC
    language:
      default:
        name: ASC
        description: ''
      go:
        name: RunQueryOrderASC
        description: ''
  - value: DESC
    language:
      default:
        name: Desc
        description: ''
      go:
        name: RunQueryOrderDesc
        description: ''
```

Note that for `Desc` the casing was lost, but not for `ASC`.

Also observed this in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/data-plane/Microsoft.Synapse/preview/2019-06-01-preview/entityTypes/Pipeline.json for enum `AzureFunctionActivityMethod` where the casing for `DELETE` is lost.
