### ISSUE TITLE
Incorrect schema type when generating types annotated with format: "password"

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4014]
Executing command.

`
autorest  --version:3.2.1 --use=. C:\git\Azure\azure-rest-api-specs\specification\web\resource-manager\readme.md --tag=package-2019-08 --file-prefix="zz_generated_" --modelerfour.lenient-model-deduplication --license-header=MICROSOFT_MIT_NO_VERSION --output-folder=C:\git\Azure\autorest.go\test\web --credential-scope="https://management.azure.com//.default" --module=web --azure-arm=true
`

For type `User` in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/CommonDefinitions.json#L2521, the type for the following fields is incorrect.

- publishingPassword
- publishingPasswordHash
- publishingPasswordSalt

The type should be `string` for all three but we get types like `User-properties-publishingPassword`.

```yaml
  credentials:
    - &ref_444
      type: credential
      apiVersions:
        - version: '2019-08-01'
      language:
        default:
          name: User-properties-publishingPassword
          description: Password used for publishing.
        go:
          name: User-properties-publishingPassword
          description: Password used for publishing.
      protocol: {}
```

Autorest core version 3.2.1
M4 version 4.18.0
