### ISSUE TITLE
File  is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#4052]
**Describe the bug**

I have approximately the following configuration.

```yaml
use-extension:
  "@microsoft.azure/autorest.typescript": "2.6.0"
  "@microsoft.azure/autorest.csharp": "2.3.82"

input-file: Api.json
directive:
- from: openapi-document
  where: $.components.schemas.*.additionalProperties
  transform: |
    return typeof $ === "boolean"
      ? ($ ? { type: "object" } : undefined)
      : $
  reason: polyfill
```

On autorest 3.1.2 everything fine
```
> autorest

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.1.2; node: v15.7.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (3.1.4).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      'C:\Users\kant\.autorest\@autorest_core@3.2.4\node_modules\@autorest\core\dist' (3.2.4)
INFORMATION: > Loading AutoRest extension '@microsoft.azure/autorest.typescript' (2.6.0->2.6.0)
INFORMATION: > Loading AutoRest extension '@microsoft.azure/autorest.csharp' (2.3.82->2.3.82)
INFORMATION: > Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
INFORMATION: The output folder doesn't contain a pre-existing package.json file to get the package version from.
[29.68 s] Generation Complete
```

if I update to 3.1.4

```
> autorest

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.1.4; node: v15.7.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\user\.autorest\@microsoft.azure_autorest-core@2.0.4419\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4419)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (2.6.0->2.6.0)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (2.3.82->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
FATAL: swagger-document/loader - FAILED
FATAL: Error: File 'Api.json' is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')
Process() cancelled due to exception : File 'Api.json' is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')
  Error: File 'Api.json' is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')
```

Api.json is valid OpenAPI 3.0 definition file, also notice that core module selected differently between versions.

**Expected behavior**
Does not matter what way is right, would be good to have consistent behaviour in core modules selection. Would be good if this process would be documented, so it can be tested.

**Comment by timotheeguerin** [comment]
HI @kant2002, not exactly sure how it was working before, you are using the old generators which were meant to work with core version 2.x and do not support openapi v3(Hence why they say this is not a valid swagger version).
  "@microsoft.azure/autorest.typescript": "2.6.0"
  "@microsoft.azure/autorest.csharp": "2.3.82"
Did it actually generate sdks?

You can try using `@autorest/csharp` and `@autorest/typescript` instead for the latest generators.

Also seeing your directives if this was meant to workaround addtionalProperties: true I believe this is resolve in the latest versions

**Comment by kant2002** [comment]
I do not super attached to old generators, just want to have stable configuration which I can safely replace. 
Unfortunately I try other newer configuration and in one or another way they are not working
- I switch to `@autorest/csharp` and `@autorest/typescript` latest versions, but I have problem with `csharp` output directory settings does not picked up. Actually based on inspection of `configuration.yaml` seems to be `output-folder` which appears after `csharp` and `typescript` overrides generated location path.
- I completely remove `use` directive from my MD file, but on 3.1.2 or 3.1.4 I hit https://github.com/Azure/autorest/issues/3560 so probably these issues indeed somewhat related.

**Comment by timotheeguerin** [comment]
how are you defining the csharp output directory for it not to be picked up?

For the directive I meant I don't think you need this section anymore
```yaml
directive:
- from: openapi-document
  where: $.components.schemas.*.additionalProperties
  transform: |
    return typeof $ === "boolean"
      ? ($ ? { type: "object" } : undefined)
      : $
  reason: polyfill
```

**Comment by kant2002** [comment]
Because I receive bunch of files in the `generated` folder. instead of my `clientproj\generated`. Also if I specify `--output-artifact=configuration.yaml` it also appears in the `generated` folder, and not in the root folder. I do not have top level `output-directory: xxx` in the MD file.
I do use only `autorest` command line

**Comment by timotheeguerin** [comment]
are you specifying `output-folder` anywhere in your config? By default the output-folder will be `./generated` as you are seeing. I am not sure how the older csharp generator was working but I would look at this for the latest version https://github.com/Azure/autorest.csharp#use-outside-of-the-azure-sdk-net-repo

**Comment by kant2002** [comment]
```
input-file: Project.Api/obj/Project.Api.json
csharp:
- output-folder: Project.Api.Client/Generated
  namespace: Project.Api.Client
  use-datetimeoffset: true
typescript:
- output-folder : public/app/services/api
  enum-types: true
```

**Comment by kant2002** [comment]
Plus obviously regular header. But this is all YAML what I have in MD file.

```
# Project API
> see https://aka.ms/autorest
```

Header like that and yaml near the backticks

**Comment by kant2002** [comment]
[api.md](https://github.com/Azure/autorest/files/6298371/api.md)

Just to add to your confusion 😄

**Comment by kant2002** [comment]
hold on. I lots in the issues and variations.

```
```yaml
use-extension:
  "@microsoft.azure/autorest.typescript": "2.6.0"
  "@microsoft.azure/autorest.csharp": "2.3.82"

input-file: Project.Api/obj/Project.Api.json
csharp:
  - output-folder: Project.Api.Client/Generated
    namespace: Project.Api.Client
	use-datetimeoffset: true
typescript:
- output-folder : public/app/services/api
  enum-types: true
```
```

**Comment by timotheeguerin** [comment]
Ok, so I believe the issue here is how the new generator is defined it won't load config nested under `csharp`

The recommended way is to do this and run one generator at the time using `--csharp` or `--typescript`. 

````md

```yaml
input-file: Project.Api/obj/Project.Api.json
```

```yaml $(csharp)
input-file: Project.Api/obj/Project.Api.json
output-folder: Project.Api.Client/Generated
namespace: Project.Api.Client
use-datetimeoffset: true
```

```yaml $(typescript)
output-folder: public/app/services/api
enum-types: true
```

````
