### ISSUE TITLE
Per-language directive not being applied.

### ISSUE THREAD

**Issue by jviau** [Azure/autorest#4055]
**Describe the bug**
Using a directive per-language is not being applied, as documented here: http://azure.github.io/autorest/user/literate-file-formats/configuration.html#directives---global-or-per-language

Autorest version 3.0.6339 -- (3.1.* errors out for me, opening a different issue).

Input yaml config:
Does not work (wrapped in a `$(csharp)` condition):
```yaml
csharp:
  directive:
    - where: "$.definitions.*.properties.properties"
      transform: >-
        $["x-ms-client-flatten"] = false;
        return $;
```

Works:
```yaml
directive:
  - where: "$.definitions.*.properties.properties"
    transform: >-
      $["x-ms-client-flatten"] = false;
      return $;
```

**Expected behavior**
The directive is applied when generating CSharp code.

**Comment by timotheeguerin** [comment]
Which csharp generator are you using? Believe this is the same issue as https://github.com/Azure/autorest.csharp/issues/1146

You can either replace `csharp` with `csharpgen` or use conditional blocks

````md
```yaml $(csharp)
 directive:
    - where: "$.definitions.*.properties.properties"
      transform: >-
        $["x-ms-client-flatten"] = false;
        return $;
```
````

**Comment by jviau** [comment]
Can you clarify what you mean by "replace `csharp` with `csharpgen`"? If you mean this:

```yaml
csharpgen:
  directive:
    - where: "$.definitions.*.properties.properties"
      transform: >-
        $["x-ms-client-flatten"] = false;
        return $;
```

I just tried it and it does not work.

Autorest.csharp is 2.3.91.

And I already have all of this in a `$(csharp)` conditional block - exactly like what you linked. The problem with that is this will impact _other_ languages if they are generated at the same time. IE: `autorest --csharp --typescript`, typescript will get the transform as well - I want it to apply to CSharp only. Maybe that is just not supported?
