### ISSUE TITLE
Regression: ChoiceSchema modeled without values

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#4062]
Input https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/cognitiveservices/data-plane/AnomalyDetector/readme.md

``` yaml
choices:
    - !ChoiceSchema &ref_12
      choices:
        - !ChoiceValue 
          language:
            default:
              name: InvalidCustomInterval
              description: ''
        - !ChoiceValue 
          language:
            default:
              name: BadArgument
              description: ''
        - !ChoiceValue 
          language:
            default:
              name: InvalidGranularity
              description: ''
        - !ChoiceValue 
          language:
            default:
              name: InvalidPeriod
              description: ''
        - !ChoiceValue 
          language:
            default:
              name: InvalidModelArgument
              description: ''
```
