### ISSUE TITLE
Document credential-types/credential-scopes/credential-header-name and which auth types requires which one

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4126]
In [this PR](https://github.com/Azure/autorest.csharp/pull/1234#discussion_r631299662), I'm documenting it for the LLC work (since it requires them set), but it was correctly pointed out that this really belongs in autorest documentation.

**Something like**

To do this, first one of two supported credential-types needed to be defined in the readme.md or autorest.md file:

Just Key Credential:
```yaml
credential-types: AzureKeyCredential
credential-header-name: Your-Subscription-Key
```

Just Token Credential:
```yaml
credential-types: TokenCredential
credential-scopes: https://yourendpoint.azure.com/.default
```

Both Credentials:
```yaml
credential-types: TokenCredential;AzureKeyCredential
credential-header-name: Your-Subscription-Key
credential-scopes: https://yourendpoint.azure.com/.default
```
