### ISSUE TITLE
Syntax Help - Operation rename

### ISSUE THREAD

**Issue by hsbrown2** [Azure/autorest#4159]
https://github.com/Azure/autorest/blob/main/docs/generate/directives.md#operation-rename

Following the guidance above, I'm trying to resolve some errors due to missing operationId elements, which generates errors like this:

ERROR (Interpretations): NEED 'operationId' for 'get' operation on path '/api/adapters'

If I clone the code snippet located at the above link into the readme.md with appropriate paths and my operationId, it does not seem to have any effect:

### Directive renaming operation from "getVirtualMachine" to "getVM"
directive:
  from: swagger-document
  where: '$.paths["/vm"].get'
  transform: >
    $["operationId"] = "getVM";

I surmised that the problem here is that operationId does not exist in the original file, so it can't change something that doesn;t exist, so I tried some of what fearthecowboy posted here: https://github.com/Azure/autorest/issues/2647

directive:
  from: swagger-document # do it globally 
  where: $.paths.*.* 
  
  transform: $.operationId = `Transport_${$.tags[0]}`

Essentially changing the where clause to the $.paths from the first snippet and the transform to something for my needs, but no joy.

I'd also like to do this for a couple dozen paths - can there be multiple directives? How to?

Here's an example of my attempt(s):

directive:
  from: swagger-document
  where: '$.paths["/api/adapters"].get'
  transform: $.operationId = "Get-Adapter";

TIA

**Comment by timotheeguerin** [comment]
Hi @hsbrown2, 
yes you can have multiple. The directive entry can either be a single entry or an array.

So you can do something like that.
```yaml
directive:
  - from: swagger-document
    where: '$.paths["/api/adapters"].get'
    transform: $.operationId = "Get-Adapter";
 - from: swagger-document
    where: '$.paths["/api/adapters2"].get'
    transform: $.operationId = "Get-Adapter2";
```
