### ISSUE TITLE
Syntax Help - Multiple Directives

### ISSUE THREAD

**Issue by hsbrown2** [Azure/autorest#4161]
So you can do something like that.
```yaml
directive:
  - from: swagger-document
    where: '$.paths["/api/adapters"].get'
    transform: $.operationId = "Get-Adapter";
 - from: swagger-document
    where: '$.paths["/api/adapters2"].get'
    transform: $.operationId = "Get-Adapter2";
```

_Originally posted by @timotheeguerin in https://github.com/Azure/autorest/issues/4159#issuecomment-857768649_

Using this convention, I'm still running into trouble. The first directive seems to parse just fine, but subsequent ones appear to not work as expected. I have 60 operationId transforms to add. If I add a second one it doesn't seem to have any impact:

directive:
  - from: openapi-document
    where: '$.paths["/api/adapters"].get'
    transform: $.operationId = "Get-ProductAdapter";
  - from: openapi-document
    where: '$.paths["/api/adapters/{adapter_name}/{node_id}/upload_file"].put'
    transform: $.operationId = "Put-ProductAdapter";

The first one appears to be parsed as expected (the error is gone), but the second one does not. I'm copying the path from the error, and changing the verb (sort of as an assumption based on the examples) at the end, although perhaps this isn't correct. Or maybe the curly braces are tripping things up an I need to escape them... Any transforms after the first continue to generate errors. I'm just guessing at this point! Any ides?

Thank you so much for the assists!
