### ISSUE TITLE
Using `require` for a multi-RP service needs filtering

### ISSUE THREAD

**Issue by heaths** [Azure/autorest#4176]
There's a strong desire in the Azure SDKs to simply use `require` instead of `input-file` to reference autorest configuration - so that most configuration can be shared.

This is a problem for services that have multiple resource providers, or are otherwise consider sub-services like Cognitive Language Services which currently contain Question Answering (nee QnA Maker) and Conversation (nee LUIS).

Similar to the transform directives, perhaps we can use filtering like so to achieve the desired results:

``` yaml
require: https://github.com/.../readme.md
where: # or maybe `filter`
- foo.json
- bar.json
  # but not baz.json
```

**Comment by timotheeguerin** [comment]
There is a few issue I have with this.

1. The configuration loading in autorest is already extremely complex, adding additional abstraction  will make it hard to implement, understand and there will always be something else that can't be done and needs to be added.
2. The way it is described here, wouldn't even work. The where is at the same level as the require and there is no good way for the configuration to understand this is relevant to that require. Could have something like that instead
```yaml
require: 
  file: https://github.com/.../readme.md
  where: 
    - foo.json
    - bar.json
```
3. Why is this even needed, can't the readme.md that is required not include the list of `input-file` or put it behind a guard so you can then just have that 
```yaml
require: https://github.com/.../readme.md
input-file:
- foo.json
- bar.json
```

If this is actually needed because the required readme has to have the list of input-files and they can't be put behind a flag. I think the best solution is to think of having a way to **override** a list config instead of appending to it. For example, could have something like that:

```yaml
require: https://github.com/.../readme.md
input-file.SET: 
- foo.json
- bar.json
```

or have the input-file list be a gitignore pattern(Prefix with `-` to remove inputs).

```yaml
require: https://github.com/.../readme.md
input-file: 
- "-foo.json"
```
