### ISSUE TITLE
[v3] Support source code transformations

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest#4179]
In the earlier versions of Autorest (V2), we used to have logic for source code transformations. For example, you can find the transformations set in https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/search/data-plane/Azure.Search/readme.md.  (Search for source-file-csharp)

But, in the latest versions of Autorest (V3), the source code transformations are not supported (Swagger Transformations are supported) I have confirmed with @timotheeguerin the same. 

Based on that discussion, I am creating this issue to track the work to include source code transformations.

**Comment by timotheeguerin** [comment]
Sorry, when I said that this was an issue on the generator side. The old generator pipeline definition used to define the transform stage but they don't anymore.

See old csharp definition
https://github.com/Azure/autorest.csharp/tree/master it has this step

```yaml
  csharp/transform:
    input: simplifier
    output-artifact: source-file-csharp
    scope: scope-transform-string
```
