### ISSUE TITLE
Different description of dictionaries based upon language?

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4233]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

In https://github.com/Azure/autorest.go/issues/623 we're seeing generated code like this:
```go
	// Dictionary of
	AdditionalProperties map[string]*float32 `json:"additionalProperties,omitempty"`
```

which don't have the expected <any>

which made Joel think it was HTML stripping. However, checking the yaml, it looks like go is getting different text than other languages:

```
      language:
        default:
          name: PetAPTrue
          description: Dictionary of <any>
        go:
          name: PetAPTrue
          description: Dictionary of
          elementIsPtr: false
          marshallingFormat: json
```
and this for c#:
```
      language: !Languages 
        default:
          name: PetAPTrue
          description: Dictionary of <any>
```

**Expected behavior**

**Additional context**
I would have just transferred https://github.com/Azure/autorest.go/issues/623 over but I'm not on the team for autorest core it seems, so I don't have permissions.  

Attached the code models, but it is just a test server project.

[CodeModels.zip](https://github.com/Azure/autorest/files/6881150/CodeModels.zip)
