### ISSUE TITLE
Allow "from" and "where" when suppressing a global warning

### ISSUE THREAD

**Issue by LanceXact** [Azure/autorest#4272]
**Problem**
"from" and "where" aren't working when suppressing the following warnings:
- UnkownSecurityScheme
- CheckDuplicateSchemas
- PropertyRedeclarationWarning

**Solution**
make it so "from" and "where" work when suppressing global warnings.

Something like:

``` yaml
directive:
  - from openapi.json
    where $.components.securitySchemes.oauth2
    suppress: UnkownSecurityScheme
```

**Why?**
I don't want to hide these warnings forever in all cases. I may accidentally use an incorrect security scheme and I'd like the warning to help me in that case. However, I know for a fact oauth2 is one our application supports, and thus shouldn't present a warning.
