### ISSUE TITLE
Support for Parameter with `content.<mediaType>`

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#4303]
See openapi doc https://swagger.io/docs/specification/describing-parameters/#schema-vs-content

Parameter can either have a `schema` or  a `content` with a single media type describing how the parameter value needs to be formatted.

Example:

```yaml
  - name: select
    in: query
    description: Returns explicitly requested properties.
    content:
      application/json:
        schema:
          type: string
```

Param should look like
```
?select="myquery in quote"
```
