### ISSUE TITLE
Investigate properties with allOf to a ref

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#4336]
In openapi you cannot use any properties next to a `$ref``. Autorest does allow a few to be able to be used on model properties like `description`, `readonly`, etc.

```yaml
Foo:
  name: 
    readOnly: true
    $ref: "#components/schemas/name"
``` 

However it should really be defined this way

```yaml
Foo:
  name: 
    readOnly: true
    allOf: 
     - $ref: "#components/schemas/name"
``` 

Autorest does support this but needs a flag to be enabled `--modelerfour.remove-empty-child-schemas` and will log warnings. 
Believe we can be smart and figure out when this pattern is used and not log any warnings and remove the need for the flag.
