### ISSUE TITLE
paging.member is erroneously kept when x-ms-paging.operationName is deleted via a transform

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#4393]
In the following config.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/policyinsights/resource-manager/readme.md

The `x-ms-pageable.operationName` is deleted via a transform for a few operations.  While this removes the `language.default.paging.nextLinkOperation` from the model, the `language.default.paging.member` is still present.

The Go code generator uses the existence of `language.default.paging.member` to determine if a paged operation is to use a separate operation for fetching the next page.  Maybe this is in error?

We can work around this easily enough by predicating on the existence of `language.default.paging.nextLinkOperation`.  Just raising that there looks to be an inconsistency in this presumably rare case.

**Comment by timotheeguerin** [comment]
@jhendrixMSFT I tried to repro locally with the paging test server spec and it does remove the paging member and other naming info when removing operationName via a transform

```json
{
  "swagger": "2.0",
  "info": {
    "title": "AutoRest Paging Test Service",
    "description": "Long-running Operation for AutoRest",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "schemes": ["http"],
  "produces": ["application/json"],
  "consumes": ["application/json"],
  "paths": {
    "/paging/multiple/getWithQueryParams": {
      "get": {
        "x-ms-pageable": {
          "nextLinkName": "nextLink",
          "itemName": "values",
          "operationName": "Paging_nextOperationWithQueryParams"
        },
        "operationId": "Paging_getWithQueryParams",
        "description": "A paging operation that includes a next operation. It has a different query parameter from it's next operation nextOperationWithQueryParams. Returns a ProductResult",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Initial response with ProvisioningState='Canceled'",
            "schema": {
              "$ref": "#/definitions/ProductResult"
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductResult": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nextLink": {
          "type": "string"
        }
      }
    }
  }
}

```



```yaml
directive:
  from: swagger-document
  where: $.paths["/paging/multiple/getWithQueryParams"].get
  transform: |
    delete $["x-ms-pageable"].operationName
```

Is is maybe a mixup in which pageable gets the operationName removed and which ones have member?

**Comment by jhendrixMSFT** [comment]
Here's a snippet from the yaml.
```
          x-ms-pageable:
            nextLinkName: '@odata.nextLink'
            operationName: PolicyEvents_NextLink
        language:
          default:
            name: ListQueryResultsForManagementGroup
            description: Queries policy events for the resources under the management group.
            paging:
              group: PolicyEvents
              member: NextLink
              nextLinkName: '@odata.nextLink'
```
