### ISSUE TITLE
Generate DTO's Only

### ISSUE THREAD

**Issue by bholemaharaj** [Azure/autorest#4422]
- The code listed above didn't work for me, it still generated everything and all I wanted was just the models(DTO's)
- Here is my reademe.md.

``` yaml
# it's the same options as command line options, just drop the double-dash!
input-file: input/myApi.json
powershell: true
output-folder: output/V1
namespace: CodeGen

directive:
  # removes all the operations from the code generation (leaves behind empty serviceclient though)
  - from: "code-model-v1" 
    where: $.operations[*]
    transform: return undefined
  
  # removes all the rest of the files that we don't want. (ie, if they say "using Models") 
  - from: source-file-csharp
    where: $
    transform: if ($.includes("using Models;")) return "";
```

- What is - from: code-model-v1 and  - from: source-file-csharp?

_Originally posted by @bholemaharaj in https://github.com/Azure/autorest/issues/2847#issuecomment-1036441181_
