### ISSUE TITLE
Ability to specify Logging level for a single plugin

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#4441]
Sometime you could want to get more verbose logging but only for a specific plugin.

## Solution:

Via flag
```
--<scope>.log-level=debug
--<scope>.verbose
--<scope>.debug
```

Via config
```yaml
<scope>: 
  logLevel: 'debug'
  verbose: true
  debug: true
```

### Examples:

Via flag
```
# Set logging level to debug for modelerfour
--modelerfour.log-level=debug

# Set logging level to verbose for modelerfour
--<scope>.verbose

# Set logging level to debug for modelerfour
--<scope>.debug
```

Via config
```yaml
# Set logging level to debug for modelerfour
modelerfour: 
  logLevel: 'debug'

# Set logging level to verbose for modelerfour
modelerfour: 
  verbose: true

# Set logging level to debug for modelerfour
modelerfour: 
  debug: true
```
