### ISSUE TITLE
x-ms-client-name ignored for object that is array item

### ISSUE THREAD

**Issue by markm77** [Azure/autorest#4470]
**Before filling a bug**

- [x ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x ] have you checked existing issues

**Describe the bug**

I have been trying to generate C# models from the following file: https://github.com/OpenBankingUK/read-write-api-specs/blob/v3.1.8r5/dist/openapi/account-info-openapi.yaml (NB "servers" property of this file should be edited/removed to avoid a trivial error).

This file has extensive nesting of arrays which leads to long class names (and for me in fact causes AutoRest to crash I believe due to 260-character path length limit if no endpoints are removed).

The problem names I need to make shorter are those which are types for array item objects, i.e. names of things with type `object` which sit under `items` in the OpenAPI file.

It seems there is no way to shorten these names. The example below demonstrates the problem. We wish to change the class name for an element (item) of Address from OBParty2AddressItem to MyTest2 but ` x-ms-client-name` is ignored.

```yaml
    OBParty2:
      type: "object"
        properties:
          Address:
          type: "array"
          x-ms-client-name: "MyTest1" # does not influence item type name which is still OBParty2AddressItem rather than OBParty2MyTest1Item
          items:
            x-ms-client-name: "MyTest2" # ignored; item type name is still OBParty2AddressItem
            type: "object"
            properties:
```

This limitation causes me great trouble in trying to generate models from this file. I am not using any significant AutoRest options apart from specifying the C# generator.

Can you please update `x-ms-client-name` so that it works for array item objects? Or provide another means to shorten the client names generated for array item objects?

BR,
Mark

**Comment by timotheeguerin** [comment]
Hi @markm77 should have a fix for that here https://github.com/Azure/autorest/pull/4474#issuecomment-1069631965

could you confirm this is resolving your problem by adding `--version:https://tinyurl.com/y89cunyr` as the comment on the PR suggest

**Comment by markm77** [comment]
Thanks very much for the super-fast response! It's midnight here but I'll try this tomorrow. BR, Mark

**Comment by markm77** [comment]
Hi @timotheeguerin , thanks very much for your change which I've done some testing with.

Your fix works fine at a single level although I've noticed name changes don't propagate through the hierarchy.

For example, taking this case:

```yaml
    OBReadBalance1:
      type: "object"
      required:
        - "Data"
      properties:
        Data:
          type: "object"
          properties:
            Balance:
              type: "array"
              items:
                x-ms-client-name: "MyTest1"
                type: "object"
                properties:
                  CreditLine:
                    type: "array"
                    items:
                      #x-ms-client-name: "MyTest2"
                      type: "object"
                      description: "Set of elements used to provide details on the credit line."
```

Your change fixes the type name for a `Balance` element to be `MyTest1` rather than `OBReadBalance1DataBalanceItem` as before.

However your change does not adjust the name of a `CreditLine` element which remains `OBReadBalance1DataBalancePropertiesItemsItem`. This is not too bad - just means I need to write a transform to rename every single type name in the hierarchy.

However I've noticed another similar propagation issue which limits my ability to constrain type name lengths.

Look at this example:

```yaml
    OBReadBalance1:
      type: "object"
      x-ms-client-name: "MyTest1"
      required:
        - "Data"
      properties:
        Data:
          x-ms-client-name: "MyTest2"
          type: "object"
``` 

The type name for the Data property is not influenced by `x-ms-client-name` and remains `OBReadBalance1Data` rather than e.g. `MyTest1MyTest2`. This means I can't control length growth of these type names. Is there anything that can be done about this?

Anyway many thanks again for your change and responding so quickly.

BR,
Mark
