### ISSUE TITLE
Potential behavior change / bug in modelerfour 4.23.0

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest#4476]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Swagger https://github.com/Azure/autorest.testserver/blob/main/swagger/body-byte.json#L86-L114

Parameter output of 4.22.3
```
              - &ref_10
                schema: *ref_9
                implementation: Method
                required: true
                language:
                  default:
                    name: byteBody
                    description: Base64-encoded non-ascii byte string hex(FF FE FD FC FB FA F9 F8 F7 F6)
                protocol:
                  http:
                    in: body
                    style: json

  byteArrays:
    - &ref_9
      type: byte-array
      format: byte
      apiVersions:
        - version: 1.0.0
      language:
        default:
          name: ByteArray
          description: Base64-encoded non-ascii byte string hex(FF FE FD FC FB FA F9 F8 F7 F6)
      protocol: {}
```

Parameter output of 4.23.0
```
              - &ref_9
                schema: *ref_0
                implementation: Method
                required: true
                language:
                  default:
                    name: byteBody
                    description: Base64-encoded non-ascii byte string hex(FF FE FD FC FB FA F9 F8 F7 F6)
                protocol:
                  http:
                    in: body
                    style: binary

  strings:
    - &ref_0
      type: string
      language:
        default:
          name: String
          description: simple string
      protocol: {}
```

See that the `schema` of the `parameter` changed from type `byteArray` to `string`. (however `protocol.http.style` changed from `json` to `binary`)

There seems similar problem with `date-time` and `duration`. E.g. https://github.com/Azure/autorest.testserver/blob/main/swagger/body-duration.json#L50-L59 (again `ref_0` is string)
```
              - &ref_7
                schema: *ref_0
                implementation: Method
                required: true
                language:
                  default:
                    name: durationBody
                    description: duration body
                protocol:
                  http:
                    in: body
                    style: binary
```

```
Please provide as much information as you can. This would be:
- OpenAPI files having the issues https://github.com/Azure/autorest.testserver/blob/main/swagger/body-byte.json#L86-L114
- Autorest command used 
```
autorest core is 3.8.0

**Expected behavior**

**Additional context**
