### ISSUE TITLE
Align property type name to re-named object type name

### ISSUE THREAD

**Issue by markm77** [Azure/autorest#4479]
Sometimes it is necessary to rename client type names to deal with extremely long names as described in #4470 .

When renaming an object using `x-ms-client-name`, unfortunately the property type name is not also updated.

For example, in the following code `OBReadBalance1` is renamed to `MyTest1`.  Yet the property type name (in C#) for the Data property remains `OBReadBalance1Data` and there is no way to change this. I believe the property type name should respect the `x-ms-client-name` setting for the object and become `MyTest1Data`.

```
    OBReadBalance1:
      type: "object"
      x-ms-client-name: "MyTest1"
      required:
        - "Data"
      properties:
        Data:
          type: "object"
```

I believe solving this would mean there is a way to reduce the length of any type name (this seems the only unsolved case) and thus deal with problems caused by heavily nested OpenAPI files (see #4470 for an example).

BR,
Mark
