### ISSUE TITLE
Code model of StatusCode generates $ref value

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest#4523]
Swagger: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/communication/data-plane/CallingServer/preview/2021-06-15-preview/communicationservicescallingserver.json
The operation `ServerCalls_StopRecording` and `ServerCalls_PauseRecording` generates code model with responses as below:
```
- !Response 
  language: !Languages 
    default:
      name: ''
  protocol: !Protocols 
    http: !HttpResponse 
      statusCodes:
        - $ref
```
The statusCodes is invalid.
