### ISSUE TITLE
M4 should accept both `format: url` and `format: uri` and return `type :uri`

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest#4571]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Right now, the endpoint parameter in `x-ms-parameterized-host` should be declared as `url` format. But in Swagger spec, it's recommended to use `uri` as the format value, which is true for many existing Azure REST specs.

For the swagger definition below:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "2020-12-01",
    "title": "AccessControlClient"
  },
  "x-ms-parameterized-host": {
    "hostTemplate": "{endpoint}",
    "useSchemePrefix": true,
    "parameters": [
      {
        "$ref": "#/parameters/Endpoint"
      }
    ]
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/test": {
      "get": {
        "tags": [
          "test"
        ],
        "operationId": "test",
        "consumes": [
          "application/json",
          "text/json"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/ApiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Success response.",
            "schema": {
                "type": "string"
            }
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "schema": {
                "type": "string"
            }
          }
        }
      }
    }
  },
  "parameters": {
    "Endpoint": {
      "name": "endpoint",
      "description": "The workspace development endpoint, for example https://myworkspace.dev.azuresynapse.net.",
      "required": true,
      "type": "string",
      "format": "url",
      "in": "path",
      "x-ms-skip-url-encoding": true,
      "x-ms-parameter-location": "client"
    },
    "ApiVersionParameter": {
      "name": "api-version",
      "in": "query",
      "required": true,
      "type": "string",
      "description": "The Synapse client API Version."
    }
  }
}
```

If I specify `"format": "url"` for `Endpoint` parameter, then there will be a UriSchema in the generated M4 output:

```yaml
uris:
    - !UriSchema &ref_1
      type: uri
      language: !Languages 
        default:
          name: Endpoint
          description: ''
      protocol: !Protocols {}
```

If I specify `"format": "uri"`, then it changes to a StringSchema.

```yaml
- !StringSchema &ref_1
      type: string
      language: !Languages 
        default:
          name: Endpoint
          description: ''
      protocol: !Protocols {}
```

---

**Expected behavior**

We should support `uri` as a valid `format` value.

**Additional context**

`DeviceUpdate` defines the [endpoint parameter](https://github.com/Azure/azure-rest-api-specs/blob/9cdc63d02deb911ab06571cbe309c860cc0f1ded/specification/deviceupdate/data-plane/Microsoft.DeviceUpdate/preview/2022-07-01-preview/deviceupdate.json#L4335) under `parameters` section of swagger file, which triggers linter error since `url` is not a valid input. If they changed it to `uri`, it can pass linter but will not generate the correct codes due to the schema change.
