### ISSUE TITLE
Custom Go Autorest UserAgent

### ISSUE THREAD

**Issue by mirusky** [Azure/autorest#4585]
Before asking the question:

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [X] have you checked existing issues for a similar question?

----------------
I'm currently testing the code generation for study and POC purposes. 

I've have checked in issues, documentation about flags, generating, specific languages ... But I wasn't able to find a properly way to change the UserAgent. 

I'm stuck with the following piece of code:

``` go
// UserAgent returns the UserAgent string to use when sending http.Requests.
func UserAgent() string {
    return "Azure-SDK-For-Go/" + Version() + " petstore/1.0.0"
}
```

This is how my readme config looks like:

``` yaml 
input-file: pétstöre.json     # full Unicode support

go:
  # low-level-client: true    # not so sure how it's affect the client
  clear-output-folder: true 
  package-name: test/petstore # golang import package
  namespace: petstore         # the main package name 
  output-folder: petstore     # where generated code goes
  trace: true                 # enables tracinng support
  eol: lf                     # sets end of line as linux/windows
```

My question is how to change the value in UserAgent ? 

``` go
// Eg:
func UserAgent() string {
    return "MyAwesomeUserAgent/" + Version() + " petstore/1.0.0"
}
```
