### ISSUE TITLE
suppression in the readme doesn't work

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#4620]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

for example:
run below command 
```
npx autorest --v3 --version:next --spectral --validation --azure-validator --semantic-validator=false --model-validator=false  --openapi-type=arm --use=@microsoft.azure/openapi-validator@2.0.0-beta.3 --tag=package-2021-12-01 https://github.com/openapi-env-test/azure-rest-api-specs/blob/01f0f6d8ee9880bf72bb7e5f1bb2db9614ab0153/specification/vmware/resource-manager/readme.md

```
the readme contains suppression, but the error of PathResourceProviderNamePascalCase weren't suppressed
```
  - suppress: PathResourceProviderNamePascalCase
    from: Microsoft.AVS/stable/2021-12-01/vmware.json
    reason: Microsoft.AVS was chosen over Microsoft.AzureVMwareSolution
```

**Expected behavior**

the related error won't be shown

**Comment by timotheeguerin** [comment]
Seems to be an issue with casing `PathResourceProviderNamePascalCase`. If you need to be unblocked now use `suppress: pathresourceprovidernamepascalcase`

Using the `suppress` directive is also deprecated. You can use the `suppression` entry which make it a seperate from transform directives

```yaml
suppressions:
  - code: pathresourceprovidernamepascalcase
    from: Microsoft.AVS/stable/2021-12-01/vmware.json
    reason: Microsoft.AVS was chosen over Microsoft.AzureVMwareSolution
```

**Comment by cataggar** [comment]
> code was compared to a lower case value

`PathResourceProviderNamePascalCase` seems to be the only with problems. `pathresourceprovidernamepascalcase` worked. The rest of these also worked:

``` yaml
  - code: XmsLongRunningOperationOptions
  - code: UnSupportedPatchProperties
  - code: LroLocationHeader
  - code: PatchSkuProperty
  - code: LroPatch202
  - code: DefinitionsPropertiesNamesCamelCase
  - code: IgnoredPropertyNextToRef
```
