### ISSUE TITLE
Unable to connect while allowInsecureConnection is false

### ISSUE THREAD

**Issue by MarcErdmann** [Azure/autorest#4623]
**Describe the bug**
I have used the following config to generate an SDK:
```yaml
input-file: ./swagger/openapi.yaml
title: users-service-sdk
allow-insecure-connection: true

typescript:
  output-folder: sdk
  clear-output-folder: true
  generate-metadata: true
  allow-insecure-connection: true
  add-credential: false
```

I use the SDK like this:
```typescript
const sdk = new UsersServiceSdk({ $host: 'http://...' });
```

I get the following error when using the SDK:
`Error: Cannot connect to <domain> while allowInsecureConnection is false.`

**Expected behavior**
I expect the SDK to not complain about an http domain if I set `allow-insecure-connection` in the config. Was this setting removed? How can I use Autorest to build SDKs for http (non-https) endpoints?
