### ISSUE TITLE
Naming overrides not working as expected via `x-ms-client-name` or Modelerfour config

### ISSUE THREAD

**Issue by MarcErdmann** [Azure/autorest#4626]
**Describe the bug**

From my understanding, Autorest supports the override of property names. I followed the example given by @timotheeguerin  here:
https://github.com/Azure/autorest/issues/3830#issuecomment-771732557

Additionally I tried to use the OpenAPI extension `x-ms-client-name` described here:
https://github.com/stankovski/AutoRest/blob/master/Documentation/swagger-extensions.md#generic-extensions

The forced renaming is working only half way. The name changes, but in both cases the property name got converted to the convention of each language (camelcase for Typescript) still.

I use OpenAPI v3 and Autorest `^3.6.1`.

**Expected behavior**
I expect that the property name stays exactly the same (including casing) if I set an override via either the OpenAPI extension `x-ms-client-name` or the Modelerfour naming override config.

**Comment by timotheeguerin** [comment]
This is by design. Autorest target many different languages, `x-ms-client-name` it designed to provide a better name for client but it will then still apply the style of the language to get the final name. 

However the modelerfour config works as expected(on modelerfour side). The resulting codemodel respected the override
<img width="251" alt="image" src="https://user-images.githubusercontent.com/1031227/188140790-17baee46-207b-4064-8d6a-cc80833636c0.png">

```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        exp:
          type: string
```

```yaml
modelerfour:
  naming: 
    override: 
        exp: GPS_GID
```

So this looks like the typescript generator is reapplying the camelCase style on top of m4, this seems like a bug there.
