### ISSUE TITLE
Directive - Add Properties 

### ISSUE THREAD

**Issue by AndrewCS149** [Azure/autorest#4627]
I'm currently trying to generate the C-Sharp SDK but need to add a property to our Swagger. Is there a way to do this with **using directives**? I have looked over plenty of documentation but can only find operations related to modifying or removing properties. 

Example: 

The line with the red arrow does not exist in the swagger and I need to add it. 
![image](https://user-images.githubusercontent.com/52691521/188952001-cdaf1fed-287d-47ba-ae12-9a0962e73e7b.png)

Thank you for any help!

**Comment by timotheeguerin** [comment]
Hey @AndrewCS149 Something like that?
```yaml
directive:
  from: swagger-document
  where: "$.definitions.Foo.properties"
  transform: |
    $.myProp = {...}
```

**Comment by AndrewCS149** [comment]
Hey @timotheeguerin. Thanks for the response. So in my case, would it look similar to this? I can't seem to pin down the exact syntax 


```json
directive: 
  - from: swagger.json
    where: $definitions.AssignmentReportProperties.properties
    transform: |
      $.format = duration
```

**Comment by timotheeguerin** [comment]
Oh sorry thought you meant an full openapi3 property. If you just want to update a json property that looks about good expect `duration` must be in quotes `"duration"`.

The content of transform is just Javascript code. 

Your directive should be 

```yaml
  - from: swagger.json
    where: $definitions.AssignmentReportProperties.properties.duration
    transform: |
      $.format = "duration"
```
