### ISSUE TITLE
Can't generate with "vesrion-tolerant" in swagger readme settings

### ISSUE THREAD

**Issue by YalinLi0312** [Azure/autorest#4635]
**Before filling a bug**

- [ ] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [ ] have you checked existing issues

**Describe the bug**
The error thrown when I trying to regenerate python appconfiguration package.
- Autorest command used: 
    `autorest --python --v3 .\swagger\README.md`
- I set version-tolerant: false in swagger readme, the full readme is:
```
## Azure Appconfiguration for Python

### Settings
``` yaml
input-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/appconfiguration.json
output-folder: "../azure/appconfiguration/_generated"
namespace: azure.appconfiguration
no-namespace-folders: true
python: true
python-mode: create
license-header: MICROSOFT_MIT_NO_VERSION
package-name: azure-appconfiguration
clear-output-folder: true
enable-xml: true
vanilla: true
vesrion-tolerant: false
```

**Expected behavior**
Generate the package without errors.

**Additional context**
The error I got:
![image](https://user-images.githubusercontent.com/20915761/191380341-7dae77a1-c48a-481d-86be-a4b6170ef5be.png)

**Comment by iscai-msft** [comment]
@YalinLi0312 I don't think this has to do with the flag `version-tolerant` specifically, I recently ran into this issue with `--cadl-init`

**Comment by timotheeguerin** [comment]
can you share the entire readme, right now it looks like this could be due to the `yaml` code block not being closed

**Comment by YalinLi0312** [comment]
Oh, it is closed, I removed the last line to make the description looks better.
Here's the entire readme:
## Azure Appconfiguration for Python

### Settings
``` yaml
input-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/appconfiguration.json
output-folder: "../azure/appconfiguration/_generated"
namespace: azure.appconfiguration
no-namespace-folders: true
python: true
python-mode: create
license-header: MICROSOFT_MIT_NO_VERSION
package-name: azure-appconfiguration
clear-output-folder: true
enable-xml: true
vanilla: true
models-mode: msrest
```
