### ISSUE TITLE
Path  ApiVersion exposed by M4 as query parameter

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#4659]
Full spec:
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/AnomalyDetector

```json
    "ApiVersion": {
      "name": "ApiVersion",
      "description": "Anomaly Detector API version (for example, v1.1).",
      "x-ms-parameter-location": "client",
      "x-ms-api-version": true,
      "required": true,
      "type": "string",
      "in": "path"
    }
```

M4:
```yaml
  - &ref_115
    schema: *ref_113
    implementation: Client
    origin: modelerfour:synthesized/api-version
    required: true
    language:
      default:
        name: api_version
        description: Api Version
        serializedName: ApiVersion
    protocol:
      http:
        in: query
```
