### ISSUE TITLE
Unclear Error Message

### ISSUE THREAD

**Issue by cwray-tech** [Azure/autorest#4792]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
I am getting the error:
```
fatal   | TypeError: Cannot read properties of undefined (reading 'schema')
fatal   | Process() cancelled due to failure
error   |   Error: Plugin modelerfour reported failure.
```
The issue is that it does not tell me where the error exists, and what is wrong with the openapi file.

**Our autorest.md file:**
```yaml
input-file: storage/app/openapi.json
typescript: true
output-folder: ts-sdk
clear-output-folder: true
security: AzureKey
```
**Comand run**
` autorest autorest.md `

**Expected behavior**
The error should share the line where the error is coming from. More information should be shared so that we can address it.
