### ISSUE TITLE
override-client-name doesn't allow for periods

### ISSUE THREAD

**Issue by benwa** [Azure/autorest#4987]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
When building a PowerShell module, I see that `override-client-name` removes all periods, which are a valid character.

**Expected behavior**
Periods are not removed from the module name.

**Additional context**
See `PagerDutyEventsV1`, which should be `PagerDuty.EventsV1`. You can see that periods are allowed, as both `Microsoft.PowerShell.Management` and `Microsoft.PowerShell.Utility` include them.
```powershell
S /home/ben [PagerDutyEventsV1]> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Typ…
Script     0.1.0                 PagerDutyEventsV1                   New-EventV1
Script     2.3.5                 PSReadLine                          {Get-PSReadLineKeyHa…
```

readme.md
```markdown
    ```yaml
    powershell: true
    clear-output-folder: true
    license-header: MICROSOFT_MIT_NO_VERSION
    ```
    
    ```yaml $(tag) == 'events-v1'
    namespace: PagerDuty.EventsV1
    override-client-name: PagerDuty.EventsV1
    input-file: events-v1.json
    output-folder: events-v1
    directive:
    - select: command
      where:
        subject: (^V1)(.*)
      set:
        subject: $2V1
    - where:
        parameter-name: Client
      set:
        parameter-name: ClientName
    ```
```
